# Generated by Django 5.0.14 on 2026-04-18 19:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(help_text='رقم مرجعي داخلي فريد لعملية الدفع', max_length=100, unique=True, verbose_name='رقم الدفع')),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('PROCESSING', 'قيد المعالجة'), ('PAID', 'مدفوع'), ('PARTIALLY_PAID', 'مدفوع جزئيًا'), ('FAILED', 'فشل'), ('CANCELLED', 'ملغي'), ('REFUNDED', 'مسترد'), ('PARTIALLY_REFUNDED', 'مسترد جزئيًا')], default='PENDING', max_length=30, verbose_name='حالة الدفع')),
                ('payment_method', models.CharField(choices=[('CASH', 'نقدي'), ('BANK_TRANSFER', 'تحويل بنكي'), ('CREDIT_CARD', 'بطاقة ائتمانية'), ('DEBIT_CARD', 'بطاقة مدى / خصم'), ('WALLET', 'محفظة'), ('APPLE_PAY', 'Apple Pay'), ('STC_PAY', 'STC Pay'), ('TAMARA', 'تمارا'), ('TABBY', 'تابي'), ('OTHER', 'أخرى')], default='CASH', max_length=30, verbose_name='طريقة الدفع')),
                ('provider', models.CharField(choices=[('INTERNAL', 'داخلي'), ('TAP', 'Tap'), ('TAMARA', 'Tamara'), ('TABBY', 'Tabby'), ('MANUAL', 'يدوي'), ('OTHER', 'أخرى')], default='INTERNAL', max_length=20, verbose_name='مزود الدفع')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='المبلغ')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='المبلغ المدفوع')),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='المبلغ المسترد')),
                ('currency', models.CharField(default='SAR', max_length=10, verbose_name='العملة')),
                ('external_reference', models.CharField(blank=True, help_text='رقم العملية لدى مزود الدفع أو البنك', max_length=255, verbose_name='مرجع خارجي')),
                ('transaction_id', models.CharField(blank=True, max_length=255, verbose_name='Transaction ID')),
                ('gateway_response_code', models.CharField(blank=True, max_length=100, verbose_name='Gateway Code')),
                ('gateway_message', models.TextField(blank=True, verbose_name='رسالة البوابة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('failure_reason', models.TextField(blank=True, verbose_name='سبب الفشل')),
                ('initiated_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت بدء الدفع')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت السداد')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاسترداد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customer', verbose_name='العميل')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'المدفوعات',
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order'], name='payments_order_i_b32b33_idx'), models.Index(fields=['customer'], name='payments_custome_8fefc3_idx'), models.Index(fields=['payment_number'], name='payments_payment_c27a96_idx'), models.Index(fields=['status'], name='payments_status_d621e5_idx'), models.Index(fields=['payment_method'], name='payments_payment_ee488d_idx'), models.Index(fields=['provider'], name='payments_provide_b98dc8_idx'), models.Index(fields=['paid_at'], name='payments_paid_at_c989bb_idx')],
            },
        ),
    ]
