# Generated by Django 5.0.14 on 2026-04-29 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('invoices', '0001_initial'),
        ('orders', '0002_order_agent_order_contract_order_provider_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='accounting_entry_reference',
            field=models.CharField(blank=True, help_text='مرجع اختياري للقيد المحاسبي المرتبط بالدفع.', max_length=255, verbose_name='مرجع القيد المحاسبي'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الإلغاء'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='الفاتورة المرتبطة بعملية الدفع إن وجدت.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='invoices.invoice', verbose_name='الفاتورة'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_accounting_posted',
            field=models.BooleanField(default=False, verbose_name='تم ترحيل المحاسبة'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_treasury_posted',
            field=models.BooleanField(default=False, verbose_name='تم ترحيل الخزينة'),
        ),
        migrations.AddField(
            model_name='payment',
            name='treasury_movement_reference',
            field=models.CharField(blank=True, help_text='مرجع اختياري لحركة الخزينة المرتبطة بالدفع.', max_length=255, verbose_name='مرجع حركة الخزينة'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'نقدي'), ('BANK_TRANSFER', 'تحويل بنكي'), ('CREDIT_CARD', 'بطاقة ائتمانية'), ('DEBIT_CARD', 'بطاقة مدى / خصم'), ('WALLET', 'محفظة'), ('APPLE_PAY', 'Apple Pay'), ('STC_PAY', 'STC Pay'), ('TAMARA', 'تمارا'), ('TABBY', 'تابي'), ('GATEWAY', 'بوابة دفع'), ('OTHER', 'أخرى')], default='CASH', max_length=30, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_number',
            field=models.CharField(blank=True, help_text='رقم مرجعي داخلي فريد لعملية الدفع', max_length=100, unique=True, verbose_name='رقم الدفع'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('INTERNAL', 'داخلي'), ('TAP', 'Tap'), ('TAMARA', 'Tamara'), ('TABBY', 'Tabby'), ('MANUAL', 'يدوي'), ('BANK', 'بنك'), ('OTHER', 'أخرى')], default='INTERNAL', max_length=20, verbose_name='مزود الدفع'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice'], name='payments_invoice_9dd568_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['is_treasury_posted'], name='payments_is_trea_8e7cb4_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['is_accounting_posted'], name='payments_is_acco_7f638e_idx'),
        ),
    ]
