# Generated by Django 5.0.14 on 2026-04-22 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=128, unique=True, verbose_name='Session Key')),
                ('session_version', models.PositiveIntegerField(default=1, verbose_name='Session Version')),
                ('auth_channel', models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Mobile'), ('API', 'API'), ('OTHER', 'Other')], db_index=True, default='WEB', max_length=20, verbose_name='قناة الدخول')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('device_name', models.CharField(blank=True, default='', max_length=255, verbose_name='اسم الجهاز')),
                ('device_id', models.CharField(blank=True, default='', max_length=255, verbose_name='معرف الجهاز')),
                ('location_hint', models.CharField(blank=True, default='', max_length=255, verbose_name='مؤشر الموقع')),
                ('is_current', models.BooleanField(default=False, verbose_name='الجلسة الحالية')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشطة')),
                ('logged_out_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت تسجيل الخروج')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='آخر نشاط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جلسة مستخدم نشطة',
                'verbose_name_plural': 'الجلسات النشطة',
                'ordering': ['-last_seen', '-created_at'],
                'indexes': [models.Index(fields=['user'], name='auth_center_user_id_507852_idx'), models.Index(fields=['session_key'], name='auth_center_session_0ff718_idx'), models.Index(fields=['is_active'], name='auth_center_is_acti_24cd38_idx'), models.Index(fields=['auth_channel'], name='auth_center_auth_ch_75bff5_idx'), models.Index(fields=['created_at'], name='auth_center_created_48a73c_idx'), models.Index(fields=['last_seen'], name='auth_center_last_se_d5aa0f_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('SYSTEM', 'System User'), ('COMPANY', 'Company User'), ('CUSTOMER', 'Customer'), ('AGENT', 'Agent'), ('PROVIDER', 'Provider'), ('STAFF', 'Staff'), ('PARTNER', 'Partner'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20, verbose_name='نوع المستخدم')),
                ('display_name', models.CharField(blank=True, default='', help_text='اسم العرض العام المستخدم في الواجهات والإشعارات.', max_length=255, verbose_name='الاسم المعروض')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='رابط الصورة')),
                ('bio', models.TextField(blank=True, default='', verbose_name='نبذة مختصرة')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='رقم الجوال')),
                ('whatsapp_number', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='رقم واتساب')),
                ('alternate_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='بريد إلكتروني بديل')),
                ('preferred_language', models.CharField(default='ar', max_length=10, verbose_name='اللغة المفضلة')),
                ('timezone', models.CharField(default='Asia/Riyadh', max_length=64, verbose_name='المنطقة الزمنية')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='تم توثيق الجوال')),
                ('is_whatsapp_verified', models.BooleanField(default=False, verbose_name='تم توثيق الواتساب')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='تم توثيق البريد')),
                ('is_profile_completed', models.BooleanField(default=False, verbose_name='الملف مكتمل')),
                ('tags', models.JSONField(blank=True, default=list, help_text='وسوم مرنة لتصنيف المستخدم لاحقًا بدون تعديل البنية.', verbose_name='وسوم')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='أي بيانات عامة إضافية لا تستحق إنشاء أعمدة مستقلة لها.', verbose_name='بيانات إضافية')),
                ('last_profile_update_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر تحديث للملف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف المستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_type'], name='auth_center_user_ty_a0a86b_idx'), models.Index(fields=['phone_number'], name='auth_center_phone_n_f7fff1_idx'), models.Index(fields=['whatsapp_number'], name='auth_center_whatsap_b98441_idx'), models.Index(fields=['created_at'], name='auth_center_created_9b10c5_idx')],
            },
        ),
    ]
