# Generated by Django 5.0.14 on 2026-04-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SYSTEM', 'System User'), ('STAFF', 'Staff'), ('ACCOUNTANT', 'Accountant'), ('CUSTOMER', 'Customer'), ('AGENT', 'Agent'), ('BROKER', 'Broker'), ('PROVIDER', 'Provider'), ('CENTER', 'Center'), ('PARTNER', 'Partner'), ('COMPANY', 'Company User'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30, verbose_name='نوع المستخدم'),
        ),
    ]
