# Generated by Django 5.0.14 on 2026-04-28 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_center', '0002_alter_userprofile_user_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Admin'), ('provider_admin', 'Provider Admin'), ('customer_user', 'Customer User'), ('agent_user', 'Agent User'), ('accountant', 'Accountant'), ('support', 'Support'), ('viewer', 'Viewer')], db_index=True, default='viewer', help_text='الدور الرسمي المستخدم للصلاحيات والسايدر والحماية في الواجهة والباك إند.', max_length=50, verbose_name='الدور'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='auth_center_role_b0a3a9_idx'),
        ),
    ]
