# Generated by Django 5.0.14 on 2026-05-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_center', '0003_userprofile_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Admin'), ('provider_admin', 'Provider Admin'), ('customer_user', 'Customer User'), ('agent_user', 'Agent User'), ('broker_user', 'Broker User'), ('accountant', 'Accountant'), ('support', 'Support'), ('viewer', 'Viewer')], db_index=True, default='viewer', help_text='الدور الرسمي المستخدم للصلاحيات والسايدر والحماية في الواجهة والباك إند.', max_length=50, verbose_name='الدور'),
        ),
    ]
