# Generated by Django 5.0.14 on 2026-04-18 19:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='اسم المندوب')),
                ('agent_code', models.CharField(help_text='كود داخلي أو تسويقي فريد للمندوب', max_length=50, unique=True, verbose_name='كود المندوب')),
                ('referral_code', models.CharField(help_text='الكود الذي يستخدم في البيع أو الإحالة', max_length=50, unique=True, verbose_name='كود الإحالة')),
                ('status', models.CharField(choices=[('ACTIVE', 'نشط'), ('INACTIVE', 'غير نشط'), ('SUSPENDED', 'موقوف'), ('DRAFT', 'مسودة')], default='ACTIVE', max_length=20, verbose_name='الحالة')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='رقم الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('default_commission_type', models.CharField(choices=[('PERCENTAGE', 'نسبة مئوية'), ('FIXED', 'مبلغ ثابت')], default='PERCENTAGE', max_length=20, verbose_name='نوع العمولة الافتراضي')),
                ('default_commission_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='نسبة مئوية أو مبلغ ثابت حسب النوع المحدد', max_digits=12, verbose_name='قيمة العمولة الافتراضية')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='اسم البنك')),
                ('bank_account_name', models.CharField(blank=True, max_length=255, verbose_name='اسم صاحب الحساب')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'مندوب',
                'verbose_name_plural': 'المندوبون',
                'db_table': 'agents',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['agent_code'], name='agents_agent_c_f58e92_idx'), models.Index(fields=['referral_code'], name='agents_referra_713b73_idx'), models.Index(fields=['status'], name='agents_status_f5ff61_idx'), models.Index(fields=['city'], name='agents_city_6d9e4e_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('PERCENTAGE', 'نسبة مئوية'), ('FIXED', 'مبلغ ثابت')], max_length=20, verbose_name='نوع العمولة')),
                ('commission_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة العمولة')),
                ('sales_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='قيمة البيع المحتسبة')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='قيمة العمولة المحتسبة')),
                ('referral_code_used', models.CharField(blank=True, max_length=50, verbose_name='كود الإحالة المستخدم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_orders', to='agents.agent', verbose_name='المندوب')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_orders', to='customers.customer', verbose_name='العميل')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_link', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'طلب مرتبط بمندوب',
                'verbose_name_plural': 'الطلبات المرتبطة بالمندوبين',
                'db_table': 'agent_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('EARNED', 'مستحقة'), ('APPROVED', 'معتمدة'), ('PAID', 'مدفوعة'), ('CANCELLED', 'ملغاة'), ('REVERSED', 'معكوسة')], default='PENDING', max_length=20, verbose_name='حالة العمولة')),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='قيمة الأساس')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='قيمة العمولة')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='المبلغ المصروف')),
                ('earned_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الصرف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='agents.agent', verbose_name='المندوب')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='orders.order', verbose_name='الطلب')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='payments.payment', verbose_name='الدفع المرتبط')),
                ('agent_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='agents.agentorder', verbose_name='طلب المندوب')),
            ],
            options={
                'verbose_name': 'عمولة مندوب',
                'verbose_name_plural': 'عمولات المندوبين',
                'db_table': 'agent_commissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agentorder',
            index=models.Index(fields=['agent'], name='agent_order_agent_i_261a95_idx'),
        ),
        migrations.AddIndex(
            model_name='agentorder',
            index=models.Index(fields=['customer'], name='agent_order_custome_0cf113_idx'),
        ),
        migrations.AddIndex(
            model_name='agentorder',
            index=models.Index(fields=['commission_type'], name='agent_order_commiss_fa86ac_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcommission',
            index=models.Index(fields=['agent'], name='agent_commi_agent_i_32f0b2_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcommission',
            index=models.Index(fields=['order'], name='agent_commi_order_i_a58f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcommission',
            index=models.Index(fields=['payment'], name='agent_commi_payment_7708ee_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcommission',
            index=models.Index(fields=['commission_status'], name='agent_commi_commiss_8fbad0_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcommission',
            index=models.Index(fields=['earned_at'], name='agent_commi_earned__a57f28_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcommission',
            index=models.Index(fields=['paid_at'], name='agent_commi_paid_at_18db47_idx'),
        ),
    ]
