# Generated by Django 5.0.14 on 2026-04-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='agentcommission',
            index=models.Index(fields=['approved_at'], name='agent_commi_approve_6f91c7_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcommission',
            index=models.Index(fields=['created_at'], name='agent_commi_created_da9495_idx'),
        ),
        migrations.AddIndex(
            model_name='agentorder',
            index=models.Index(fields=['created_at'], name='agent_order_created_1be842_idx'),
        ),
    ]
