# Generated by Django 5.0.14 on 2026-05-13 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentcommission_agent_commi_approve_6f91c7_idx_and_more'),
        ('customers', '0002_customerloginotp_customer_last_login_at_and_more'),
        ('orders', '0004_ordertimeline_order_assigned_for_delivery_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='agent',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة'),
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(blank=True, help_text='يربط المندوب بحساب مستخدم حتى يتم التعرف عليه تلقائيًا عند إنشاء الطلب.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_profile', to=settings.AUTH_USER_MODEL, verbose_name='مستخدم النظام المرتبط'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'نشط'), ('INACTIVE', 'غير نشط'), ('SUSPENDED', 'موقوف'), ('DRAFT', 'مسودة')], db_index=True, default='ACTIVE', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='agentcommission',
            name='approved_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الاعتماد'),
        ),
        migrations.AlterField(
            model_name='agentcommission',
            name='commission_status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('EARNED', 'مستحقة'), ('APPROVED', 'معتمدة'), ('PAID', 'مدفوعة'), ('CANCELLED', 'ملغاة'), ('REVERSED', 'معكوسة')], db_index=True, default='PENDING', max_length=20, verbose_name='حالة العمولة'),
        ),
        migrations.AlterField(
            model_name='agentcommission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='agentcommission',
            name='earned_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الاستحقاق'),
        ),
        migrations.AlterField(
            model_name='agentcommission',
            name='paid_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الصرف'),
        ),
        migrations.AlterField(
            model_name='agentorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='agentorder',
            name='referral_code_used',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='كود الإحالة المستخدم'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['user'], name='agents_user_id_17a57a_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['phone'], name='agents_phone_19cd85_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['email'], name='agents_email_968e69_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['created_at'], name='agents_created_697d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='agentorder',
            index=models.Index(fields=['referral_code_used'], name='agent_order_referra_2f3f7e_idx'),
        ),
    ]
