# Generated by Django 5.0.14 on 2026-05-19 09:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_accountingperiod_accountingroutingrule_and_more'),
        ('agents', '0003_agent_created_by_agent_updated_by_agent_user_and_more'),
        ('contracts', '0003_alter_contractproduct_options_and_more'),
        ('customers', '0002_customerloginotp_customer_last_login_at_and_more'),
        ('orders', '0005_order_contract_product_order_offer_badge_and_more'),
        ('payments', '0002_payment_accounting_entry_reference_and_more'),
        ('products', '0005_product_discount_percentage_product_has_duration_and_more'),
        ('providers', '0003_providerdocument_provider_commercial_registration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='default_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='تستخدم كقيمة افتراضية إذا كان المندوب هو مندوب التوصيل ولم توجد قاعدة خاصة.', max_digits=12, verbose_name='قيمة التوصيل الافتراضية'),
        ),
        migrations.AddField(
            model_name='agent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية'),
        ),
        migrations.AddField(
            model_name='agentcommission',
            name='is_accounting_posted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='مرحل محاسبيًا'),
        ),
        migrations.AddField(
            model_name='agentcommission',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_commissions', to='accounting.journalentry', verbose_name='قيد الاستحقاق المحاسبي'),
        ),
        migrations.AddField(
            model_name='agentcommission',
            name='journal_entry_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='مرجع القيد'),
        ),
        migrations.AddField(
            model_name='agentcommission',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية'),
        ),
        migrations.AddField(
            model_name='agentcommission',
            name='posted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الترحيل المحاسبي'),
        ),
        migrations.AddField(
            model_name='agentorder',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية'),
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الوسيط')),
                ('broker_code', models.CharField(max_length=50, unique=True, verbose_name='كود الوسيط')),
                ('referral_code', models.CharField(help_text='يستخدم عند ربط الطلبات أو الفرق بالوسيط.', max_length=50, unique=True, verbose_name='كود إحالة الوسيط')),
                ('status', models.CharField(choices=[('ACTIVE', 'نشط'), ('INACTIVE', 'غير نشط'), ('SUSPENDED', 'موقوف'), ('DRAFT', 'مسودة')], db_index=True, default='ACTIVE', max_length=20, verbose_name='الحالة')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='رقم الجوال')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='المدينة')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('default_commission_type', models.CharField(choices=[('PERCENTAGE', 'نسبة مئوية'), ('FIXED', 'مبلغ ثابت')], default='FIXED', max_length=20, verbose_name='نوع عمولة الوسيط الافتراضية')),
                ('default_commission_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='قيمة عمولة الوسيط الافتراضية')),
                ('revenue_recognition_mode', models.CharField(choices=[('GROSS_SALE', 'كامل البيع إيراد'), ('NET_PLATFORM_SHARE', 'حصة النظام فقط إيراد')], db_index=True, default='GROSS_SALE', help_text='هل كامل البيع إيراد للشركة أم حصة النظام فقط.', max_length=30, verbose_name='طريقة الاعتراف بالإيراد')),
                ('settlement_mode', models.CharField(choices=[('AGENT_LEVEL', 'التسوية على مستوى المندوب'), ('BROKER_LEVEL', 'التسوية على مستوى الوسيط'), ('AGENT_WITH_BROKER_SUMMARY', 'تفصيل مندوب مع ملخص وسيط')], db_index=True, default='AGENT_WITH_BROKER_SUMMARY', help_text='تحدد هل العهدة والتسوية على المندوب أم الوسيط.', max_length=40, verbose_name='طريقة التسوية')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='اسم البنك')),
                ('bank_account_name', models.CharField(blank=True, max_length=255, verbose_name='اسم صاحب الحساب')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brokers_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brokers_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
                ('user', models.OneToOneField(blank=True, help_text='يربط الوسيط بحساب مستخدم نوعه BROKER عند الحاجة.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_profile', to=settings.AUTH_USER_MODEL, verbose_name='مستخدم النظام المرتبط')),
            ],
            options={
                'verbose_name': 'وسيط',
                'verbose_name_plural': 'الوسطاء',
                'db_table': 'brokers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgentFinancialRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=255, verbose_name='اسم القاعدة')),
                ('rule_type', models.CharField(choices=[('PLATFORM_SHARE', 'حصة النظام'), ('BROKER_SHARE', 'حصة الوسيط'), ('SALES_COMMISSION', 'عمولة بيع'), ('DELIVERY_FEE', 'قيمة توصيل'), ('COD_COLLECTION', 'عمولة تحصيل COD'), ('PROVIDER_CONTRACT_COMMISSION', 'عمولة عقد مقدم خدمة'), ('BONUS', 'بونص'), ('DEDUCTION', 'خصم'), ('ADJUSTMENT', 'تسوية'), ('OTHER', 'أخرى')], db_index=True, max_length=50, verbose_name='نوع القاعدة')),
                ('scope', models.CharField(choices=[('GLOBAL', 'عام'), ('PRODUCT_TYPE', 'حسب نوع المنتج'), ('PRODUCT', 'حسب المنتج'), ('CONTRACT', 'حسب العقد'), ('CONTRACT_PRODUCT', 'حسب عرض مقدم الخدمة'), ('PROVIDER', 'حسب مقدم الخدمة'), ('ORDER_KIND', 'حسب نوع الطلب'), ('OTHER', 'أخرى')], db_index=True, default='GLOBAL', max_length=50, verbose_name='نطاق القاعدة')),
                ('product_type', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='نوع المنتج')),
                ('order_kind', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='نوع الطلب')),
                ('calculation_type', models.CharField(choices=[('PERCENTAGE', 'نسبة'), ('FIXED', 'مبلغ ثابت')], default='FIXED', max_length=20, verbose_name='طريقة الحساب')),
                ('calculation_base', models.CharField(choices=[('GROSS_AMOUNT', 'إجمالي المبلغ'), ('NET_BEFORE_TAX', 'الصافي قبل الضريبة'), ('TOTAL_WITH_TAX', 'الإجمالي شامل الضريبة'), ('PLATFORM_SHARE', 'حصة النظام'), ('BROKER_SHARE', 'حصة الوسيط'), ('CUSTOM_AMOUNT', 'مبلغ مخصص')], default='NET_BEFORE_TAX', max_length=40, verbose_name='أساس الحساب')),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='نسبة أو مبلغ ثابت حسب طريقة الحساب.', max_digits=12, verbose_name='القيمة')),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='حد أدنى اختياري')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='حد أعلى اختياري')),
                ('priority', models.PositiveIntegerField(db_index=True, default=100, help_text='الأولوية الأقل رقمًا تطبق أولًا عند تعدد القواعد.', verbose_name='الأولوية')),
                ('valid_from', models.DateField(blank=True, db_index=True, null=True, verbose_name='صالحة من')),
                ('valid_until', models.DateField(blank=True, db_index=True, null=True, verbose_name='صالحة حتى')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشطة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('agent', models.ForeignKey(blank=True, help_text='إذا كانت القاعدة خاصة بمندوب معين.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_rules', to='agents.agent', verbose_name='المندوب')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_financial_rules', to='contracts.contract', verbose_name='العقد')),
                ('contract_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_financial_rules', to='contracts.contractproduct', verbose_name='عرض مقدم الخدمة')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_financial_rules', to='products.product', verbose_name='المنتج')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_financial_rules', to='providers.provider', verbose_name='مقدم الخدمة')),
                ('broker', models.ForeignKey(blank=True, help_text='إذا كانت القاعدة خاصة بوسيط.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_rules', to='agents.broker', verbose_name='الوسيط')),
            ],
            options={
                'verbose_name': 'قاعدة مالية للمندوب/الوسيط',
                'verbose_name_plural': 'القواعد المالية للمندوبين والوسطاء',
                'db_table': 'agent_financial_rules',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentFinancialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=100, unique=True, verbose_name='رقم السطر المالي')),
                ('entry_type', models.CharField(choices=[('PLATFORM_SHARE', 'حصة النظام'), ('BROKER_SHARE', 'حصة وسيط'), ('SALES_COMMISSION', 'عمولة بيع'), ('DELIVERY_FEE', 'قيمة توصيل'), ('COD_CUSTODY', 'عهدة COD'), ('COD_COLLECTION_FEE', 'عمولة تحصيل COD'), ('PROVIDER_CONTRACT_COMMISSION', 'عمولة عقد مقدم خدمة'), ('CASH_SETTLEMENT', 'توريد نقدي'), ('PAYOUT', 'صرف مستحق'), ('BONUS', 'بونص'), ('DEDUCTION', 'خصم'), ('ADJUSTMENT', 'تسوية'), ('REVERSAL', 'عكس'), ('OTHER', 'أخرى')], db_index=True, max_length=50, verbose_name='نوع السطر')),
                ('direction', models.CharField(choices=[('DEBIT', 'مدين على الطرف'), ('CREDIT', 'دائن للطرف')], db_index=True, help_text='مدين على الطرف أو دائن له.', max_length=20, verbose_name='الاتجاه')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('PENDING', 'قيد الانتظار'), ('EARNED', 'مستحق'), ('APPROVED', 'معتمد'), ('SETTLED', 'مسوى'), ('PAID', 'مدفوع'), ('CANCELLED', 'ملغى'), ('REVERSED', 'معكوس')], db_index=True, default='PENDING', max_length=20, verbose_name='الحالة')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='المبلغ')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='المبلغ المسدد')),
                ('currency', models.CharField(db_index=True, default='SAR', max_length=10, verbose_name='العملة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='مرجع')),
                ('source_type', models.CharField(blank=True, db_index=True, help_text='order, treasury, settlement, manual, contract, payment...', max_length=80, verbose_name='نوع المصدر')),
                ('source_id', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='معرف المصدر')),
                ('source_number', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='رقم المصدر')),
                ('journal_entry_reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع القيد')),
                ('is_accounting_posted', models.BooleanField(db_index=True, default=False, verbose_name='مرحل محاسبيًا')),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الترحيل')),
                ('earned_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('settled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ التسوية')),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الدفع')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_entries', to='agents.agent', verbose_name='المندوب')),
                ('commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_entries', to='agents.agentcommission', verbose_name='العمولة القديمة المرتبطة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_financial_entries_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_financial_entries', to='accounting.journalentry', verbose_name='القيد المحاسبي')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_financial_entries', to='orders.order', verbose_name='الطلب')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_financial_entries', to='payments.payment', verbose_name='الدفع')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_financial_entries_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_entries', to='agents.agentfinancialrule', verbose_name='القاعدة المالية')),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_entries', to='agents.broker', verbose_name='الوسيط')),
            ],
            options={
                'verbose_name': 'سطر مالي للمندوب/الوسيط',
                'verbose_name_plural': 'السجلات المالية للمندوبين والوسطاء',
                'db_table': 'agent_financial_entries',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='broker',
            field=models.ForeignKey(blank=True, help_text='إذا كان المندوب تابعًا لوسيط أو وكيل.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='agents.broker', verbose_name='الوسيط'),
        ),
        migrations.AddField(
            model_name='agentcommission',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='agents.broker', verbose_name='الوسيط'),
        ),
        migrations.AddField(
            model_name='agentorder',
            name='broker',
            field=models.ForeignKey(blank=True, help_text='Snapshot للوسيط وقت ربط الطلب بالمندوب.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_orders', to='agents.broker', verbose_name='الوسيط'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['broker'], name='agents_broker__e44d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcommission',
            index=models.Index(fields=['broker'], name='agent_commi_broker__f23945_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcommission',
            index=models.Index(fields=['is_accounting_posted'], name='agent_commi_is_acco_363d28_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcommission',
            index=models.Index(fields=['journal_entry'], name='agent_commi_journal_f21c94_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcommission',
            index=models.Index(fields=['journal_entry_reference'], name='agent_commi_journal_0424d0_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcommission',
            index=models.Index(fields=['posted_at'], name='agent_commi_posted__86a752_idx'),
        ),
        migrations.AddIndex(
            model_name='agentorder',
            index=models.Index(fields=['broker'], name='agent_order_broker__2cac63_idx'),
        ),
        migrations.AddIndex(
            model_name='broker',
            index=models.Index(fields=['user'], name='brokers_user_id_317a82_idx'),
        ),
        migrations.AddIndex(
            model_name='broker',
            index=models.Index(fields=['broker_code'], name='brokers_broker__e927c7_idx'),
        ),
        migrations.AddIndex(
            model_name='broker',
            index=models.Index(fields=['referral_code'], name='brokers_referra_8d7691_idx'),
        ),
        migrations.AddIndex(
            model_name='broker',
            index=models.Index(fields=['status'], name='brokers_status_79e96d_idx'),
        ),
        migrations.AddIndex(
            model_name='broker',
            index=models.Index(fields=['city'], name='brokers_city_797998_idx'),
        ),
        migrations.AddIndex(
            model_name='broker',
            index=models.Index(fields=['phone'], name='brokers_phone_a8cc2e_idx'),
        ),
        migrations.AddIndex(
            model_name='broker',
            index=models.Index(fields=['email'], name='brokers_email_f7c89d_idx'),
        ),
        migrations.AddIndex(
            model_name='broker',
            index=models.Index(fields=['revenue_recognition_mode'], name='brokers_revenue_efddf2_idx'),
        ),
        migrations.AddIndex(
            model_name='broker',
            index=models.Index(fields=['settlement_mode'], name='brokers_settlem_c0f1e6_idx'),
        ),
        migrations.AddIndex(
            model_name='broker',
            index=models.Index(fields=['created_at'], name='brokers_created_8b4bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialrule',
            index=models.Index(fields=['broker'], name='agent_finan_broker__c1a48d_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialrule',
            index=models.Index(fields=['agent'], name='agent_finan_agent_i_ca9795_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialrule',
            index=models.Index(fields=['rule_type'], name='agent_finan_rule_ty_3a31a0_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialrule',
            index=models.Index(fields=['scope'], name='agent_finan_scope_a1d8cb_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialrule',
            index=models.Index(fields=['product'], name='agent_finan_product_4f4ddf_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialrule',
            index=models.Index(fields=['product_type'], name='agent_finan_product_6061f0_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialrule',
            index=models.Index(fields=['contract'], name='agent_finan_contrac_68f9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialrule',
            index=models.Index(fields=['contract_product'], name='agent_finan_contrac_aa6088_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialrule',
            index=models.Index(fields=['provider'], name='agent_finan_provide_b278d3_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialrule',
            index=models.Index(fields=['order_kind'], name='agent_finan_order_k_9f5f5b_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialrule',
            index=models.Index(fields=['calculation_type'], name='agent_finan_calcula_f12842_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialrule',
            index=models.Index(fields=['calculation_base'], name='agent_finan_calcula_82edf8_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialrule',
            index=models.Index(fields=['priority'], name='agent_finan_priorit_45efbe_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialrule',
            index=models.Index(fields=['is_active'], name='agent_finan_is_acti_bbaa3e_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialrule',
            index=models.Index(fields=['valid_from', 'valid_until'], name='agent_finan_valid_f_511302_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialentry',
            index=models.Index(fields=['agent'], name='agent_finan_agent_i_f7af59_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialentry',
            index=models.Index(fields=['broker'], name='agent_finan_broker__589171_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialentry',
            index=models.Index(fields=['order'], name='agent_finan_order_i_520583_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialentry',
            index=models.Index(fields=['payment'], name='agent_finan_payment_621822_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialentry',
            index=models.Index(fields=['commission'], name='agent_finan_commiss_614085_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialentry',
            index=models.Index(fields=['rule'], name='agent_finan_rule_id_075808_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialentry',
            index=models.Index(fields=['entry_number'], name='agent_finan_entry_n_1ec30c_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialentry',
            index=models.Index(fields=['entry_type'], name='agent_finan_entry_t_4c2a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialentry',
            index=models.Index(fields=['direction'], name='agent_finan_directi_3f8fdc_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialentry',
            index=models.Index(fields=['status'], name='agent_finan_status_e18495_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialentry',
            index=models.Index(fields=['currency'], name='agent_finan_currenc_dae298_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialentry',
            index=models.Index(fields=['reference'], name='agent_finan_referen_dade47_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialentry',
            index=models.Index(fields=['source_type'], name='agent_finan_source__7125da_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialentry',
            index=models.Index(fields=['source_id'], name='agent_finan_source__1349cf_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialentry',
            index=models.Index(fields=['source_number'], name='agent_finan_source__370a55_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialentry',
            index=models.Index(fields=['journal_entry'], name='agent_finan_journal_12bf60_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialentry',
            index=models.Index(fields=['journal_entry_reference'], name='agent_finan_journal_439ed8_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialentry',
            index=models.Index(fields=['is_accounting_posted'], name='agent_finan_is_acco_a91921_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialentry',
            index=models.Index(fields=['earned_at'], name='agent_finan_earned__9f5bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialentry',
            index=models.Index(fields=['approved_at'], name='agent_finan_approve_919838_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialentry',
            index=models.Index(fields=['settled_at'], name='agent_finan_settled_98b7f4_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialentry',
            index=models.Index(fields=['paid_at'], name='agent_finan_paid_at_9b916e_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialentry',
            index=models.Index(fields=['posted_at'], name='agent_finan_posted__027958_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialentry',
            index=models.Index(fields=['created_at'], name='agent_finan_created_f5e6c7_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialentry',
            index=models.Index(fields=['entry_type', 'status'], name='agent_finan_entry_t_72916a_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinancialentry',
            index=models.Index(fields=['source_type', 'source_id'], name='agent_finan_source__0e8192_idx'),
        ),
    ]
