# Generated by Django 5.0.14 on 2026-04-18 19:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('order_items', '0001_initial'),
        ('orders', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='رقم مرجعي داخلي فريد للفاتورة', max_length=100, unique=True, verbose_name='رقم الفاتورة')),
                ('invoice_type', models.CharField(choices=[('SALES', 'فاتورة مبيعات'), ('TAX', 'فاتورة ضريبية'), ('SIMPLIFIED', 'فاتورة مبسطة'), ('CREDIT_NOTE', 'إشعار دائن'), ('DEBIT_NOTE', 'إشعار مدين')], default='SALES', max_length=20, verbose_name='نوع الفاتورة')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('ISSUED', 'مصدرة'), ('PARTIALLY_PAID', 'مدفوعة جزئيًا'), ('PAID', 'مدفوعة'), ('OVERDUE', 'متأخرة'), ('CANCELLED', 'ملغاة'), ('REFUNDED', 'مستردة')], default='DRAFT', max_length=20, verbose_name='حالة الفاتورة')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإصدار')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الإجمالي قبل الخصم والضريبة')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي الخصم')),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='المبلغ الخاضع للضريبة')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='نسبة الضريبة')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='قيمة الضريبة')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الإجمالي النهائي')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='المبلغ المدفوع')),
                ('due_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='المبلغ المتبقي')),
                ('currency', models.CharField(default='SAR', max_length=10, verbose_name='العملة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('internal_notes', models.TextField(blank=True, verbose_name='ملاحظات داخلية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer', verbose_name='العميل')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='الوصف')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='سعر الوحدة')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الخصم')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الإجمالي')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice', verbose_name='الفاتورة')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='order_items.orderitem', verbose_name='عنصر الطلب')),
            ],
            options={
                'verbose_name': 'عنصر فاتورة',
                'verbose_name_plural': 'عناصر الفواتير',
                'db_table': 'invoice_items',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='المبلغ المربوط')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الربط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payments', to='invoices.invoice', verbose_name='الفاتورة')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_links', to='payments.payment', verbose_name='الدفعة')),
            ],
            options={
                'verbose_name': 'دفعة فاتورة',
                'verbose_name_plural': 'دفعات الفواتير',
                'db_table': 'invoice_payments',
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='invoices_invoice_7778bc_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['order'], name='invoices_order_i_2507ee_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer'], name='invoices_custome_ba8289_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoices_status_07776b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_type'], name='invoices_invoice_bcf470_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date'], name='invoices_issue_d_6fe766_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='invoices_due_dat_039a25_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice'], name='invoice_ite_invoice_ab1faa_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['order_item'], name='invoice_ite_order_i_bdfbe7_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['sort_order'], name='invoice_ite_sort_or_4f153e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicepayment',
            index=models.Index(fields=['invoice'], name='invoice_pay_invoice_b58bb5_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicepayment',
            index=models.Index(fields=['payment'], name='invoice_pay_payment_6ef1ec_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicepayment',
            index=models.Index(fields=['applied_at'], name='invoice_pay_applied_3062fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoicepayment',
            unique_together={('invoice', 'payment')},
        ),
    ]
