# Generated by Django 5.0.14 on 2026-04-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='الاسم الرسمي للجهة المقدمة للخدمة', max_length=255, unique=True, verbose_name='اسم الجهة')),
                ('code', models.CharField(help_text='كود داخلي فريد للربط والإدارة', max_length=50, unique=True, verbose_name='كود الجهة')),
                ('provider_type', models.CharField(choices=[('HOSPITAL', 'مستشفى'), ('MEDICAL_CENTER', 'مركز طبي'), ('PHARMACY', 'صيدلية'), ('PARTNER', 'شريك'), ('LAB', 'مختبر'), ('CLINIC', 'عيادة'), ('OTHER', 'أخرى')], default='OTHER', max_length=30, verbose_name='نوع الجهة')),
                ('status', models.CharField(choices=[('ACTIVE', 'نشط'), ('INACTIVE', 'غير نشط'), ('SUSPENDED', 'موقوف'), ('DRAFT', 'مسودة')], default='ACTIVE', max_length=20, verbose_name='الحالة')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='الشخص المسؤول')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='رقم الهاتف')),
                ('mobile', models.CharField(blank=True, max_length=30, verbose_name='رقم الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='الحي / المنطقة')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('google_maps_link', models.URLField(blank=True, verbose_name='رابط خرائط جوجل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_featured', models.BooleanField(default=False, help_text='تستخدم لإبراز الجهة في الواجهات أو العروض', verbose_name='جهة مميزة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'جهة خدمة',
                'verbose_name_plural': 'جهات الخدمة',
                'db_table': 'providers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['provider_type'], name='providers_provide_2b0409_idx'), models.Index(fields=['status'], name='providers_status_d8f0d1_idx'), models.Index(fields=['city'], name='providers_city_f2da9f_idx'), models.Index(fields=['is_featured'], name='providers_is_feat_1a6e83_idx')],
            },
        ),
    ]
