# Generated by Django 5.0.14 on 2026-05-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['name', 'city', 'area'], 'verbose_name': 'جهة خدمة', 'verbose_name_plural': 'جهات الخدمة'},
        ),
        migrations.AddField(
            model_name='provider',
            name='external_reference',
            field=models.CharField(blank=True, help_text='رقم أو معرف خارجي من الملف عند توفره', max_length=100, verbose_name='مرجع خارجي'),
        ),
        migrations.AddField(
            model_name='provider',
            name='import_key',
            field=models.CharField(blank=True, help_text='مفتاح داخلي يمنع تكرار السجل عند الاستيراد من Excel', max_length=500, null=True, unique=True, verbose_name='مفتاح الاستيراد'),
        ),
        migrations.AddField(
            model_name='provider',
            name='import_source',
            field=models.CharField(blank=True, help_text='مثال: medical_network_excel', max_length=100, verbose_name='مصدر الاستيراد'),
        ),
        migrations.AddField(
            model_name='provider',
            name='last_imported_at',
            field=models.DateTimeField(blank=True, help_text='آخر مرة تم فيها إنشاء أو تحديث السجل من ملف استيراد', null=True, verbose_name='آخر استيراد'),
        ),
        migrations.AddField(
            model_name='provider',
            name='region',
            field=models.CharField(blank=True, help_text='المنطقة الإدارية القادمة من ملف الشبكة أو الإدخال اليدوي', max_length=100, verbose_name='المنطقة'),
        ),
        migrations.AddField(
            model_name='provider',
            name='source_category',
            field=models.CharField(blank=True, help_text='التصنيف كما ورد في ملف Excel مثل مستشفى، مجمع، عيادة، مختبر', max_length=150, verbose_name='التصنيف من المصدر'),
        ),
        migrations.AddField(
            model_name='provider',
            name='street',
            field=models.CharField(blank=True, max_length=150, verbose_name='الشارع'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(help_text='الاسم الرسمي للجهة المقدمة للخدمة', max_length=255, verbose_name='اسم الجهة'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['name'], name='providers_name_7e730c_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['code'], name='providers_code_25cbfd_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['region'], name='providers_region_d6f439_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['area'], name='providers_area_b3799a_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['source_category'], name='providers_source__ac691d_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['import_key'], name='providers_import__c1640a_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['import_source'], name='providers_import__581b99_idx'),
        ),
    ]
