# Generated by Django 5.0.14 on 2026-05-09 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_provider_options_provider_external_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('logo', 'شعار مقدم الخدمة'), ('image', 'صورة مقدم الخدمة'), ('product_image', 'صورة منتج / خدمة'), ('contract_file', 'ملف عقد'), ('commercial_registration', 'ملف السجل التجاري'), ('tax_certificate', 'الشهادة الضريبية'), ('license', 'ترخيص'), ('other', 'ملف آخر')], default='other', max_length=50, verbose_name='نوع الملف')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='عنوان الملف')),
                ('description', models.TextField(blank=True, verbose_name='وصف الملف')),
                ('file_url', models.URLField(max_length=1000, verbose_name='رابط الملف')),
                ('drive_file_id', models.CharField(blank=True, max_length=255, verbose_name='Google Drive File ID')),
                ('drive_folder_id', models.CharField(blank=True, max_length=255, verbose_name='Google Drive Folder ID')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='اسم الملف الأصلي')),
                ('content_type', models.CharField(blank=True, max_length=150, verbose_name='نوع المحتوى')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='حجم الملف بالبايت')),
                ('is_primary', models.BooleanField(default=False, help_text='يستخدم لتمييز الشعار أو الصورة الرئيسية عند الحاجة', verbose_name='ملف رئيسي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'مرفق مقدم خدمة',
                'verbose_name_plural': 'مرفقات مقدمي الخدمة',
                'db_table': 'provider_documents',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='provider',
            name='commercial_registration',
            field=models.CharField(blank=True, help_text='رقم السجل التجاري لمقدم الخدمة', max_length=100, verbose_name='السجل التجاري'),
        ),
        migrations.AddField(
            model_name='provider',
            name='drive_folder_id',
            field=models.CharField(blank=True, help_text='معرف مجلد مقدم الخدمة في Google Drive', max_length=255, verbose_name='Google Drive Folder ID'),
        ),
        migrations.AddField(
            model_name='provider',
            name='drive_folder_url',
            field=models.URLField(blank=True, help_text='الرابط العام أو الإداري لمجلد مقدم الخدمة في Google Drive', max_length=1000, verbose_name='رابط مجلد Google Drive'),
        ),
        migrations.AddField(
            model_name='provider',
            name='image_drive_file_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Google Drive File ID للصورة'),
        ),
        migrations.AddField(
            model_name='provider',
            name='image_url',
            field=models.URLField(blank=True, help_text='الرابط العام للصورة بعد رفعها إلى Google Drive', max_length=1000, verbose_name='رابط صورة مقدم الخدمة'),
        ),
        migrations.AddField(
            model_name='provider',
            name='logo_drive_file_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Google Drive File ID للشعار'),
        ),
        migrations.AddField(
            model_name='provider',
            name='logo_url',
            field=models.URLField(blank=True, help_text='الرابط العام للشعار بعد رفعه إلى Google Drive', max_length=1000, verbose_name='رابط شعار مقدم الخدمة'),
        ),
        migrations.AddField(
            model_name='provider',
            name='name_ar',
            field=models.CharField(blank=True, help_text='الاسم العربي الرسمي لمقدم الخدمة', max_length=255, verbose_name='اسم الجهة بالعربي'),
        ),
        migrations.AddField(
            model_name='provider',
            name='name_en',
            field=models.CharField(blank=True, help_text='الاسم الإنجليزي الرسمي لمقدم الخدمة', max_length=255, verbose_name='اسم الجهة بالإنجليزي'),
        ),
        migrations.AddField(
            model_name='provider',
            name='tax_number',
            field=models.CharField(blank=True, help_text='الرقم الضريبي / رقم ضريبة القيمة المضافة', max_length=100, verbose_name='الرقم الضريبي'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(help_text='اسم الجهة المستخدم للتوافق الخلفي والبحث العام', max_length=255, verbose_name='اسم الجهة'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['name_ar'], name='providers_name_ar_584444_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['name_en'], name='providers_name_en_26c421_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['commercial_registration'], name='providers_commerc_f6c025_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['tax_number'], name='providers_tax_num_714c20_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['drive_folder_id'], name='providers_drive_f_4671cc_idx'),
        ),
        migrations.AddField(
            model_name='providerdocument',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='providers.provider', verbose_name='مقدم الخدمة'),
        ),
        migrations.AddField(
            model_name='providerdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_provider_documents', to=settings.AUTH_USER_MODEL, verbose_name='تم الرفع بواسطة'),
        ),
        migrations.AddIndex(
            model_name='providerdocument',
            index=models.Index(fields=['provider', 'file_type'], name='provider_do_provide_303248_idx'),
        ),
        migrations.AddIndex(
            model_name='providerdocument',
            index=models.Index(fields=['provider', 'is_primary'], name='provider_do_provide_eb0c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='providerdocument',
            index=models.Index(fields=['drive_file_id'], name='provider_do_drive_f_b34a55_idx'),
        ),
        migrations.AddIndex(
            model_name='providerdocument',
            index=models.Index(fields=['drive_folder_id'], name='provider_do_drive_f_519b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='providerdocument',
            index=models.Index(fields=['created_at'], name='provider_do_created_5bc141_idx'),
        ),
    ]
