# Generated by Django 5.0.14 on 2026-05-20 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_providerdocument_provider_commercial_registration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='user',
            field=models.OneToOneField(blank=True, help_text='حساب الدخول الرئيسي لمقدم الخدمة، ينشأ اختياريًا عند إنشاء أو تفعيل العقد.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب مستخدم مقدم الخدمة'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['user'], name='providers_user_id_5aead7_idx'),
        ),
    ]
