# Generated by Django 5.0.14 on 2026-04-18 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='اسم واضح للعقد ليسهل التعرف عليه', max_length=255, verbose_name='عنوان العقد')),
                ('contract_number', models.CharField(help_text='رقم مرجعي فريد للعقد', max_length=100, unique=True, verbose_name='رقم العقد')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('ACTIVE', 'نشط'), ('EXPIRED', 'منتهي'), ('TERMINATED', 'ملغي'), ('SUSPENDED', 'موقوف')], default='DRAFT', max_length=20, verbose_name='حالة العقد')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ بداية العقد')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية العقد')),
                ('signed_at', models.DateField(blank=True, null=True, verbose_name='تاريخ التوقيع')),
                ('provider_contact_name', models.CharField(blank=True, max_length=255, verbose_name='اسم مسؤول الجهة')),
                ('provider_contact_phone', models.CharField(blank=True, max_length=30, verbose_name='جوال مسؤول الجهة')),
                ('provider_contact_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد مسؤول الجهة')),
                ('pricing_model', models.CharField(choices=[('FIXED', 'سعر ثابت'), ('PERCENTAGE', 'نسبة'), ('CUSTOM', 'مخصص'), ('FREE', 'مجاني')], default='CUSTOM', max_length=20, verbose_name='آلية التسعير')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='خصم عام على مستوى العقد إن وجد', max_digits=5, verbose_name='نسبة الخصم العامة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات داخلية')),
                ('terms_and_conditions', models.TextField(blank=True, verbose_name='الشروط والأحكام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='providers.provider', verbose_name='الجهة المقدمة للخدمة')),
            ],
            options={
                'verbose_name': 'عقد',
                'verbose_name_plural': 'العقود',
                'db_table': 'contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, help_text='يستخدم إذا كان للمنتج سعر خاص ضمن العقد', max_digits=12, null=True, verbose_name='سعر خاص')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='خصم خاص لهذا المنتج داخل العقد', max_digits=5, verbose_name='نسبة الخصم الخاصة')),
                ('coverage_notes', models.TextField(blank=True, help_text='تفاصيل أو شروط خاصة بهذا المنتج ضمن العقد', verbose_name='ملاحظات التغطية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_products', to='contracts.contract', verbose_name='العقد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_contracts', to='products.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'منتج داخل عقد',
                'verbose_name_plural': 'منتجات العقود',
                'db_table': 'contract_products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='contracts_status_093df1_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['provider'], name='contracts_provide_2a0e32_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['start_date'], name='contracts_start_d_b96943_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['end_date'], name='contracts_end_dat_9bf3b4_idx'),
        ),
        migrations.AddIndex(
            model_name='contractproduct',
            index=models.Index(fields=['contract'], name='contract_pr_contrac_fa1392_idx'),
        ),
        migrations.AddIndex(
            model_name='contractproduct',
            index=models.Index(fields=['product'], name='contract_pr_product_4841a7_idx'),
        ),
        migrations.AddIndex(
            model_name='contractproduct',
            index=models.Index(fields=['is_active'], name='contract_pr_is_acti_4f40e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractproduct',
            unique_together={('contract', 'product')},
        ),
    ]
