# Generated by Django 5.0.14 on 2026-04-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='system_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='نسبة Primey Care من العمليات أو الخدمات المرتبطة بهذا العقد', max_digits=5, verbose_name='نسبة النظام'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['pricing_model'], name='contracts_pricing_31a9fe_idx'),
        ),
    ]
