# Generated by Django 5.0.14 on 2026-05-14 12:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_system_commission_percentage_and_more'),
        ('products', '0004_alter_product_slug'),
        ('providers', '0003_providerdocument_provider_commercial_registration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractproduct',
            options={'ordering': ['priority', '-is_featured', '-created_at'], 'verbose_name': 'منتج داخل عقد', 'verbose_name_plural': 'منتجات العقود'},
        ),
        migrations.AlterUniqueTogether(
            name='contractproduct',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contractproduct',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='عرض مميز'),
        ),
        migrations.AddField(
            model_name='contractproduct',
            name='marketing_image_alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='النص البديل لصورة العرض'),
        ),
        migrations.AddField(
            model_name='contractproduct',
            name='marketing_image_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='رابط صورة العرض'),
        ),
        migrations.AddField(
            model_name='contractproduct',
            name='offer_badge',
            field=models.CharField(blank=True, help_text='مثال: عرض خاص، الأكثر طلبًا، خصم محدود.', max_length=100, verbose_name='شارة العرض'),
        ),
        migrations.AddField(
            model_name='contractproduct',
            name='offer_description',
            field=models.TextField(blank=True, verbose_name='وصف العرض'),
        ),
        migrations.AddField(
            model_name='contractproduct',
            name='offer_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية العرض'),
        ),
        migrations.AddField(
            model_name='contractproduct',
            name='offer_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية العرض'),
        ),
        migrations.AddField(
            model_name='contractproduct',
            name='offer_subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='وصف مختصر للعرض'),
        ),
        migrations.AddField(
            model_name='contractproduct',
            name='offer_terms',
            field=models.TextField(blank=True, verbose_name='شروط العرض'),
        ),
        migrations.AddField(
            model_name='contractproduct',
            name='offer_title',
            field=models.CharField(blank=True, help_text='عنوان تسويقي يظهر في صفحة الهبوط أو التطبيق.', max_length=255, verbose_name='عنوان العرض'),
        ),
        migrations.AddField(
            model_name='contractproduct',
            name='price_after_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='السعر النهائي المعروض للعميل بعد الخصم.', max_digits=12, null=True, verbose_name='السعر بعد الخصم'),
        ),
        migrations.AddField(
            model_name='contractproduct',
            name='price_before_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='السعر الفعلي للمنتج لدى مقدم الخدمة قبل الخصم.', max_digits=12, null=True, verbose_name='السعر قبل الخصم'),
        ),
        migrations.AddField(
            model_name='contractproduct',
            name='priority',
            field=models.PositiveIntegerField(default=100, help_text='كلما كان الرقم أقل ظهر العرض قبل غيره.', verbose_name='ترتيب العرض'),
        ),
        migrations.AddField(
            model_name='contractproduct',
            name='show_on_landing',
            field=models.BooleanField(default=False, verbose_name='إظهار في صفحة الهبوط'),
        ),
        migrations.AddField(
            model_name='contractproduct',
            name='show_on_mobile',
            field=models.BooleanField(default=False, verbose_name='إظهار في التطبيق'),
        ),
        migrations.AddField(
            model_name='contractproduct',
            name='show_on_offers',
            field=models.BooleanField(default=False, verbose_name='إظهار في صفحة العروض'),
        ),
        migrations.AddField(
            model_name='contractproduct',
            name='system_commission_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='إن تركت فارغة سيتم استخدام نسبة النظام من العقد.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة النظام الخاصة'),
        ),
        migrations.AddField(
            model_name='contractproduct',
            name='terms',
            field=models.TextField(blank=True, help_text='شروط تنفيذ أو استخدام هذا المنتج لدى مقدم الخدمة.', verbose_name='شروط المنتج داخل العقد'),
        ),
        migrations.AddField(
            model_name='contractproduct',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='عدد مرات الاستخدام المسموح بها إن وجد.', null=True, verbose_name='حد الاستخدام'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='خصم عام على مستوى العقد إن وجد', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم العامة'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='system_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='نسبة Primey Care من العمليات أو الخدمات المرتبطة بهذا العقد', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة النظام'),
        ),
        migrations.AlterField(
            model_name='contractproduct',
            name='coverage_notes',
            field=models.TextField(blank=True, help_text='تفاصيل أو شروط خاصة بهذا المنتج ضمن العقد.', verbose_name='ملاحظات التغطية'),
        ),
        migrations.AlterField(
            model_name='contractproduct',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='خصم خاص لهذا المنتج داخل العقد.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم الخاصة'),
        ),
        migrations.AlterField(
            model_name='contractproduct',
            name='special_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='حقل توافق قديم. يفضل استخدام السعر قبل الخصم والسعر بعد الخصم في التطوير الجديد.', max_digits=12, null=True, verbose_name='سعر خاص قديم'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='contracts_status_5577c0_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['provider', 'status'], name='contracts_provide_4c1689_idx'),
        ),
        migrations.AddIndex(
            model_name='contractproduct',
            index=models.Index(fields=['show_on_landing'], name='contract_pr_show_on_af4af5_idx'),
        ),
        migrations.AddIndex(
            model_name='contractproduct',
            index=models.Index(fields=['show_on_mobile'], name='contract_pr_show_on_b4858e_idx'),
        ),
        migrations.AddIndex(
            model_name='contractproduct',
            index=models.Index(fields=['show_on_offers'], name='contract_pr_show_on_bb8a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='contractproduct',
            index=models.Index(fields=['is_featured'], name='contract_pr_is_feat_ee34e8_idx'),
        ),
        migrations.AddIndex(
            model_name='contractproduct',
            index=models.Index(fields=['priority'], name='contract_pr_priorit_ee7f5b_idx'),
        ),
        migrations.AddIndex(
            model_name='contractproduct',
            index=models.Index(fields=['offer_start_date'], name='contract_pr_offer_s_590a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='contractproduct',
            index=models.Index(fields=['offer_end_date'], name='contract_pr_offer_e_18ffaa_idx'),
        ),
        migrations.AddIndex(
            model_name='contractproduct',
            index=models.Index(fields=['is_active', 'show_on_landing'], name='contract_pr_is_acti_92bc82_idx'),
        ),
        migrations.AddIndex(
            model_name='contractproduct',
            index=models.Index(fields=['is_active', 'show_on_offers'], name='contract_pr_is_acti_a1267d_idx'),
        ),
        migrations.AddIndex(
            model_name='contractproduct',
            index=models.Index(fields=['product', 'is_active'], name='contract_pr_product_14eff8_idx'),
        ),
        migrations.AddIndex(
            model_name='contractproduct',
            index=models.Index(fields=['contract', 'is_active'], name='contract_pr_contrac_405917_idx'),
        ),
        migrations.AddConstraint(
            model_name='contractproduct',
            constraint=models.UniqueConstraint(fields=('contract', 'product'), name='unique_contract_product'),
        ),
    ]
