# Generated by Django 5.0.14 on 2026-04-21 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الفئة')),
                ('weight', models.PositiveIntegerField(default=20, verbose_name='الوزن (%)')),
            ],
            options={
                'verbose_name': 'فئة تقييم',
                'verbose_name_plural': 'فئات التقييم',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='السؤال')),
                ('item_type', models.CharField(choices=[('SCORE', 'نقاط'), ('TEXT', 'نصي')], default='SCORE', max_length=20, verbose_name='نوع السؤال')),
                ('max_score', models.PositiveIntegerField(default=5, verbose_name='أقصى درجة')),
                ('weight', models.PositiveIntegerField(default=10, verbose_name='الوزن داخل الفئة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='performance_center.performancecategory', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'عنصر تقييم',
                'verbose_name_plural': 'عناصر التقييم',
                'ordering': ['category', 'weight', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='معرّف الجهة / الشركة')),
                ('company_name', models.CharField(blank=True, default='', max_length=255, verbose_name='اسم الجهة / الشركة')),
                ('name', models.CharField(max_length=255, verbose_name='اسم القالب')),
                ('period', models.CharField(choices=[('YEARLY', 'تقييم سنوي'), ('QUARTERLY', 'تقييم ربع سنوي'), ('MONTHLY', 'تقييم شهري')], default='YEARLY', max_length=20, verbose_name='نوع التقييم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_templates_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدّل بواسطة')),
            ],
            options={
                'verbose_name': 'قالب تقييم',
                'verbose_name_plural': 'قوالب التقييم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='معرّف الهدف / الموظف / المستخدم')),
                ('employee_name', models.CharField(blank=True, default='', max_length=255, verbose_name='اسم الهدف / الموظف')),
                ('subject_type', models.CharField(blank=True, default='EMPLOYEE', max_length=50, verbose_name='نوع الهدف')),
                ('period_label', models.CharField(max_length=255, verbose_name='دورة التقييم (مثال: 2026 Q1)')),
                ('status', models.CharField(choices=[('SELF_PENDING', 'بانتظار التقييم الذاتي'), ('MANAGER_PENDING', 'بانتظار تقييم المدير'), ('HR_PENDING', 'بانتظار تقييم الموارد البشرية'), ('COMPLETED', 'مكتمل')], default='SELF_PENDING', max_length=50, verbose_name='حالة سير العمل')),
                ('self_score', models.FloatField(blank=True, null=True, verbose_name='درجة التقييم الذاتي')),
                ('manager_score', models.FloatField(blank=True, null=True, verbose_name='درجة تقييم المدير')),
                ('hr_score', models.FloatField(blank=True, null=True, verbose_name='درجة تقييم الموارد البشرية')),
                ('final_score', models.FloatField(blank=True, null=True, verbose_name='النتيجة النهائية')),
                ('final_decision', models.CharField(choices=[('NORMAL', 'استمرار'), ('PROMOTION', 'ترقية'), ('BONUS', 'مكافأة'), ('WARNING', 'إنذار'), ('IMPROVEMENT_PLAN', 'خطة تطوير')], default='NORMAL', max_length=50, verbose_name='القرار النهائي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_reviews_created', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_reviews_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدّل بواسطة')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='performance_center.performancetemplate', verbose_name='قالب التقييم')),
            ],
            options={
                'verbose_name': 'تقييم أداء',
                'verbose_name_plural': 'تقييمات الأداء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='performancecategory',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='performance_center.performancetemplate', verbose_name='القالب'),
        ),
        migrations.CreateModel(
            name='PerformanceWorkflowStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_completed', models.BooleanField(default=False)),
                ('manager_completed', models.BooleanField(default=False)),
                ('hr_completed', models.BooleanField(default=False)),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='performance_center.performancereview', verbose_name='التقييم')),
            ],
            options={
                'verbose_name': 'سير العمل',
                'verbose_name_plural': 'سير العمل للتقييم',
            },
        ),
        migrations.CreateModel(
            name='PerformanceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_answer', models.TextField(blank=True, null=True, verbose_name='إجابة التقييم الذاتي')),
                ('manager_answer', models.TextField(blank=True, null=True, verbose_name='إجابة المدير')),
                ('hr_answer', models.TextField(blank=True, null=True, verbose_name='إجابة الموارد البشرية')),
                ('self_score', models.FloatField(blank=True, null=True, verbose_name='درجة التقييم الذاتي')),
                ('manager_score', models.FloatField(blank=True, null=True, verbose_name='درجة المدير')),
                ('hr_score', models.FloatField(blank=True, null=True, verbose_name='درجة HR')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='performance_center.performanceitem', verbose_name='العنصر')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='performance_center.performancereview', verbose_name='التقييم')),
            ],
            options={
                'verbose_name': 'إجابة تقييم',
                'verbose_name_plural': 'إجابات التقييم',
                'unique_together': {('review', 'item')},
            },
        ),
    ]
