# Generated by Django 5.0.14 on 2026-04-18 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثل: كشف طبي، أشعة، تحليل، تنظيف أسنان، عملية ولادة...', max_length=255, verbose_name='اسم الخدمة')),
                ('code', models.CharField(help_text='كود داخلي للخدمة داخل النظام', max_length=100, verbose_name='كود الخدمة')),
                ('status', models.CharField(choices=[('ACTIVE', 'نشط'), ('INACTIVE', 'غير نشط'), ('DRAFT', 'مسودة'), ('SUSPENDED', 'موقوف')], default='ACTIVE', max_length=20, verbose_name='الحالة')),
                ('coverage_type', models.CharField(choices=[('INCLUDED', 'مشمول'), ('DISCOUNTED', 'مخفض'), ('CASH_ONLY', 'نقدي فقط'), ('APPROVAL_REQUIRED', 'يتطلب موافقة'), ('NOT_INCLUDED', 'غير مشمول')], default='INCLUDED', max_length=30, verbose_name='نوع التغطية')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='وصف مختصر')),
                ('description', models.TextField(blank=True, verbose_name='الوصف التفصيلي')),
                ('execution_notes', models.TextField(blank=True, help_text='تعليمات أو ملاحظات تشغيلية خاصة بهذه الخدمة', verbose_name='ملاحظات التنفيذ')),
                ('coverage_notes', models.TextField(blank=True, verbose_name='ملاحظات التغطية')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='السعر المرجعي للخدمة قبل أي خصم أو تغطية', max_digits=12, null=True, verbose_name='السعر الأساسي')),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, help_text='سعر خاص ضمن هذا العقد إن وجد', max_digits=12, null=True, verbose_name='السعر الخاص')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='يتطلب موافقة')),
                ('max_usage_per_customer', models.PositiveIntegerField(blank=True, help_text='عدد مرات الاستخدام المسموحة لكل عميل إن وجدت', null=True, verbose_name='الحد الأقصى لكل عميل')),
                ('validity_days', models.PositiveIntegerField(blank=True, help_text='عدد الأيام المسموح فيها باستخدام هذه الخدمة بعد التفعيل أو الشراء', null=True, verbose_name='صلاحية بالأيام')),
                ('is_featured', models.BooleanField(default=False, verbose_name='خدمة مميزة')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='contracts.contract', verbose_name='العقد')),
                ('contract_product', models.ForeignKey(blank=True, help_text='اختياري في المرحلة الحالية، ويستخدم عند ربط الخدمة بمنتج محدد داخل العقد', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='contracts.contractproduct', verbose_name='المنتج داخل العقد')),
            ],
            options={
                'verbose_name': 'خدمة عقد',
                'verbose_name_plural': 'خدمات العقود',
                'db_table': 'contract_service_items',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['contract'], name='contract_se_contrac_201a6e_idx'), models.Index(fields=['contract_product'], name='contract_se_contrac_017579_idx'), models.Index(fields=['status'], name='contract_se_status_bd69bc_idx'), models.Index(fields=['coverage_type'], name='contract_se_coverag_3503e0_idx'), models.Index(fields=['is_featured'], name='contract_se_is_feat_3897ae_idx'), models.Index(fields=['sort_order'], name='contract_se_sort_or_8955c9_idx')],
                'unique_together': {('contract', 'code')},
            },
        ),
    ]
