# Generated by Django 5.0.14 on 2026-04-18 18:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        ('providers', '0001_initial'),
        ('service_items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='اسم واضح لما تم طلبه فعليًا', max_length=255, verbose_name='عنوان العنصر')),
                ('code', models.CharField(blank=True, help_text='كود داخلي أو مرجعي اختياري', max_length=100, verbose_name='كود العنصر')),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('APPROVAL_PENDING', 'بانتظار الموافقة'), ('APPROVED', 'تمت الموافقة'), ('REJECTED', 'مرفوض'), ('SCHEDULED', 'مجدول'), ('IN_PROGRESS', 'قيد التنفيذ'), ('COMPLETED', 'مكتمل'), ('CANCELLED', 'ملغي')], default='PENDING', max_length=30, verbose_name='حالة العنصر')),
                ('fulfillment_status', models.CharField(choices=[('NOT_STARTED', 'لم يبدأ'), ('PARTIAL', 'منفذ جزئيًا'), ('COMPLETED', 'منفذ بالكامل'), ('FAILED', 'فشل التنفيذ'), ('CANCELLED', 'تم الإلغاء')], default='NOT_STARTED', max_length=20, verbose_name='حالة التنفيذ')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='سعر الوحدة')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='نسبة الخصم')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='قيمة الخصم')),
                ('net_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='صافي سعر الوحدة')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الإجمالي النهائي')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='يتطلب موافقة')),
                ('approval_notes', models.TextField(blank=True, verbose_name='ملاحظات الموافقة')),
                ('execution_notes', models.TextField(blank=True, verbose_name='ملاحظات التنفيذ')),
                ('internal_notes', models.TextField(blank=True, verbose_name='ملاحظات داخلية')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='موعد التنفيذ')),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='contracts.contract', verbose_name='العقد المرجعي')),
                ('contract_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='contracts.contractproduct', verbose_name='المنتج داخل العقد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='الطلب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product', verbose_name='المنتج')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='providers.provider', verbose_name='الجهة المقدمة')),
                ('service_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='service_items.contractserviceitem', verbose_name='الخدمة التشغيلية')),
            ],
            options={
                'verbose_name': 'عنصر طلب',
                'verbose_name_plural': 'عناصر الطلبات',
                'db_table': 'order_items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order'], name='order_items_order_i_26ad88_idx'), models.Index(fields=['product'], name='order_items_product_a53db1_idx'), models.Index(fields=['provider'], name='order_items_provide_89d206_idx'), models.Index(fields=['contract'], name='order_items_contrac_262089_idx'), models.Index(fields=['service_item'], name='order_items_service_102cbd_idx'), models.Index(fields=['status'], name='order_items_status_c06719_idx'), models.Index(fields=['fulfillment_status'], name='order_items_fulfill_30f01f_idx'), models.Index(fields=['requires_approval'], name='order_items_require_d3afec_idx')],
            },
        ),
    ]
