# Generated by Django 5.0.14 on 2026-05-13 12:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_system_commission_percentage_and_more'),
        ('order_items', '0001_initial'),
        ('orders', '0004_ordertimeline_order_assigned_for_delivery_at_and_more'),
        ('products', '0004_alter_product_slug'),
        ('providers', '0003_providerdocument_provider_commercial_registration_and_more'),
        ('service_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='approval_requested_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ طلب الموافقة'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='approved_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الموافقة'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الإلغاء'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='contract_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='رقم العقد وقت الطلب'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='currency_code',
            field=models.CharField(db_index=True, default='SAR', max_length=10, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fulfillment_reference',
            field=models.CharField(blank=True, db_index=True, help_text='رقم بطاقة أو مرجع خدمة أو رقم موافقة اختياري.', max_length=120, verbose_name='مرجع التنفيذ'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_kind',
            field=models.CharField(choices=[('PRODUCT', 'منتج'), ('CARD', 'بطاقة'), ('PROGRAM', 'برنامج'), ('SERVICE', 'خدمة'), ('SUBSCRIPTION', 'اشتراك'), ('OTHER', 'أخرى')], db_index=True, default='PRODUCT', max_length=30, verbose_name='نوع العنصر'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='اسم المنتج وقت الطلب'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_type',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='نوع المنتج وقت الطلب'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='provider_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='اسم الجهة وقت الطلب'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rejected_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الرفض'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ بدء التنفيذ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='كود داخلي أو مرجعي اختياري', max_length=100, verbose_name='كود العنصر'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='قيمة خصم ثابتة على الوحدة الواحدة.', max_digits=12, verbose_name='قيمة الخصم على الوحدة'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الإكمال'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='fulfillment_status',
            field=models.CharField(choices=[('NOT_STARTED', 'لم يبدأ'), ('PARTIAL', 'منفذ جزئيًا'), ('COMPLETED', 'منفذ بالكامل'), ('FAILED', 'فشل التنفيذ'), ('CANCELLED', 'تم الإلغاء')], db_index=True, default='NOT_STARTED', max_length=30, verbose_name='حالة التنفيذ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='requires_approval',
            field=models.BooleanField(db_index=True, default=False, verbose_name='يتطلب موافقة'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='موعد التنفيذ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('APPROVAL_PENDING', 'بانتظار الموافقة'), ('APPROVED', 'تمت الموافقة'), ('REJECTED', 'مرفوض'), ('SCHEDULED', 'مجدول'), ('IN_PROGRESS', 'قيد التنفيذ'), ('COMPLETED', 'مكتمل'), ('CANCELLED', 'ملغي')], db_index=True, default='PENDING', max_length=30, verbose_name='حالة العنصر'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['contract_product'], name='order_items_contrac_15903d_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['item_kind'], name='order_items_item_ki_070942_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['scheduled_at'], name='order_items_schedul_a405e8_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['approval_requested_at'], name='order_items_approva_91db89_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['approved_at'], name='order_items_approve_9f2e76_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['fulfilled_at'], name='order_items_fulfill_735264_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['cancelled_at'], name='order_items_cancell_b23e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['currency_code'], name='order_items_currenc_293210_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product_type'], name='order_items_product_9f4c50_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['code'], name='order_items_code_8f2975_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['fulfillment_reference'], name='order_items_fulfill_0ddeb3_idx'),
        ),
    ]
