# Generated by Django 5.0.14 on 2026-05-14 14:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contractproduct_options_and_more'),
        ('order_items', '0002_orderitem_approval_requested_at_and_more'),
        ('orders', '0005_order_contract_product_order_offer_badge_and_more'),
        ('products', '0005_product_discount_percentage_product_has_duration_and_more'),
        ('providers', '0003_providerdocument_provider_commercial_registration_and_more'),
        ('service_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='offer_badge',
            field=models.CharField(blank=True, max_length=100, verbose_name='وسم العرض وقت الطلب'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='offer_source',
            field=models.CharField(choices=[('NONE', 'بدون عرض'), ('PRODUCT', 'عرض المنتج'), ('CONTRACT_PRODUCT', 'عرض مقدم الخدمة'), ('MANUAL', 'يدوي')], db_index=True, default='NONE', max_length=30, verbose_name='مصدر العرض'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='offer_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='عنوان العرض وقت الطلب'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='نسبة خصم الوحدة'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price_before_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='سعر الوحدة قبل الخصم'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='contract_product',
            field=models.ForeignKey(blank=True, help_text='العرض/السعر المختار من عقد مقدم الخدمة.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='contracts.contractproduct', verbose_name='عرض المنتج داخل العقد'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='حقل توافق قديم، تتم مزامنته مع unit_discount_percentage.', max_digits=5, verbose_name='نسبة الخصم'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='السعر النهائي للوحدة بعد الخصم. أبقي الاسم unit_price للتوافق.', max_digits=12, verbose_name='سعر الوحدة بعد الخصم'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['offer_source'], name='order_items_offer_s_14381b_idx'),
        ),
    ]
