# Generated by Django 5.0.14 on 2026-04-18 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(blank=True, db_index=True, help_text='Auto-generated unique customer code.', max_length=30, unique=True, verbose_name='Customer Code')),
                ('customer_type', models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate')], db_index=True, default='individual', max_length=20, verbose_name='Customer Type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked'), ('lead', 'Lead')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('source', models.CharField(choices=[('website', 'Website'), ('whatsapp', 'WhatsApp'), ('agent', 'Agent'), ('admin', 'Admin'), ('import', 'Import'), ('other', 'Other')], db_index=True, default='admin', max_length=20, verbose_name='Source')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Company Name')),
                ('display_name', models.CharField(blank=True, db_index=True, help_text='Calculated display name used in listings and relations.', max_length=255, verbose_name='Display Name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not_specified', 'Not Specified')], default='not_specified', max_length=20, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='National ID / Iqama')),
                ('passport_number', models.CharField(blank=True, max_length=50, verbose_name='Passport Number')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='Nationality')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Phone Number')),
                ('whatsapp_number', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='WhatsApp Number')),
                ('alternative_phone_number', models.CharField(blank=True, max_length=30, verbose_name='Alternative Phone Number')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='City')),
                ('district', models.CharField(blank=True, max_length=150, verbose_name='District')),
                ('street_address', models.CharField(blank=True, max_length=255, verbose_name='Street Address')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('national_address_text', models.TextField(blank=True, verbose_name='National Address')),
                ('notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for quick filtering.', max_length=255, verbose_name='Tags')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_code'], name='customers_c_custome_116ac0_idx'), models.Index(fields=['customer_type', 'status'], name='customers_c_custome_1c653b_idx'), models.Index(fields=['display_name'], name='customers_c_display_4c9536_idx'), models.Index(fields=['email'], name='customers_c_email_4fdeb3_idx'), models.Index(fields=['phone_number'], name='customers_c_phone_n_cabfe1_idx'), models.Index(fields=['whatsapp_number'], name='customers_c_whatsap_d4ea03_idx'), models.Index(fields=['city'], name='customers_c_city_571324_idx'), models.Index(fields=['created_at'], name='customers_c_created_1ed0f4_idx')],
            },
        ),
    ]
