# Generated by Django 5.0.14 on 2026-05-10 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLoginOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, help_text='Original phone number used for OTP request.', max_length=30, verbose_name='Phone Number')),
                ('normalized_phone', models.CharField(db_index=True, help_text='Normalized phone number used for OTP verification.', max_length=30, verbose_name='Normalized Phone Number')),
                ('code_hash', models.CharField(help_text='Hashed OTP code. Never store the raw OTP.', max_length=128, verbose_name='OTP Code Hash')),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('verify_phone', 'Verify Phone'), ('verify_whatsapp', 'Verify WhatsApp')], db_index=True, default='login', max_length=30, verbose_name='Purpose')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Expires At')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('attempts_count', models.PositiveSmallIntegerField(default=0, verbose_name='Attempts Count')),
                ('max_attempts', models.PositiveSmallIntegerField(default=5, verbose_name='Max Attempts')),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Request IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Customer Login OTP',
                'verbose_name_plural': 'Customer Login OTPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Customer Login At'),
        ),
        migrations.AddField(
            model_name='customer',
            name='normalized_phone',
            field=models.CharField(blank=True, db_index=True, help_text='Normalized unique phone number used for customer OTP login.', max_length=30, null=True, unique=True, verbose_name='Normalized Login Phone'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Phone Verified At'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Django user account used for customer portal login.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Linked User Account'),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='WhatsApp Verified At'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['normalized_phone'], name='customers_c_normali_bbe1a8_idx'),
        ),
        migrations.AddField(
            model_name='customerloginotp',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_otps', to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AddIndex(
            model_name='customerloginotp',
            index=models.Index(fields=['customer', 'purpose', 'created_at'], name='customers_c_custome_9022fc_idx'),
        ),
        migrations.AddIndex(
            model_name='customerloginotp',
            index=models.Index(fields=['normalized_phone', 'purpose', 'created_at'], name='customers_c_normali_d24ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='customerloginotp',
            index=models.Index(fields=['expires_at'], name='customers_c_expires_fcd184_idx'),
        ),
        migrations.AddIndex(
            model_name='customerloginotp',
            index=models.Index(fields=['verified_at'], name='customers_c_verifie_eaad41_idx'),
        ),
    ]
