# Generated by Django 5.0.14 on 2026-05-20 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agent_default_delivery_fee_agent_metadata_and_more'),
        ('customers', '0002_customerloginotp_customer_last_login_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Sales or delivery agent related to this customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='agents.agent', verbose_name='Linked Agent'),
        ),
        migrations.AddField(
            model_name='customer',
            name='broker',
            field=models.ForeignKey(blank=True, help_text='Broker related to this customer. Can be resolved from the selected agent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='agents.broker', verbose_name='Linked Broker'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('whatsapp', 'WhatsApp'), ('agent', 'Agent'), ('broker', 'Broker'), ('admin', 'Admin'), ('import', 'Import'), ('other', 'Other')], db_index=True, default='admin', max_length=20, verbose_name='Source'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['agent'], name='customers_c_agent_i_f2c20a_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['broker'], name='customers_c_broker__098328_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['agent', 'broker'], name='customers_c_agent_i_546e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['source'], name='customers_c_source_f6c0b3_idx'),
        ),
    ]
