# Generated by Django 5.0.14 on 2026-04-18 19:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الحساب')),
                ('code', models.CharField(help_text='كود داخلي فريد للصندوق أو البنك', max_length=50, unique=True, verbose_name='كود الحساب')),
                ('account_type', models.CharField(choices=[('CASHBOX', 'صندوق نقدي'), ('BANK', 'حساب بنكي')], max_length=20, verbose_name='نوع الحساب')),
                ('status', models.CharField(choices=[('ACTIVE', 'نشط'), ('INACTIVE', 'غير نشط'), ('SUSPENDED', 'موقوف'), ('CLOSED', 'مغلق')], default='ACTIVE', max_length=20, verbose_name='الحالة')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='الرصيد الافتتاحي')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='الرصيد الحالي')),
                ('currency', models.CharField(default='SAR', max_length=10, verbose_name='العملة')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='اسم البنك')),
                ('account_holder_name', models.CharField(blank=True, max_length=255, verbose_name='اسم صاحب الحساب')),
                ('account_number', models.CharField(blank=True, max_length=100, verbose_name='رقم الحساب')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('branch_name', models.CharField(blank=True, max_length=255, verbose_name='اسم الفرع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_default', models.BooleanField(default=False, verbose_name='حساب افتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('ledger_account', models.ForeignKey(blank=True, help_text='الحساب المقابل في دليل الحسابات', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_accounts', to='accounting.account', verbose_name='الحساب المحاسبي')),
            ],
            options={
                'verbose_name': 'حساب خزينة',
                'verbose_name_plural': 'حسابات الخزينة',
                'db_table': 'treasury_accounts',
                'ordering': ['account_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(help_text='رقم مرجعي داخلي فريد للحركة', max_length=100, unique=True, verbose_name='رقم الحركة')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'قبض'), ('EXPENSE', 'صرف'), ('TRANSFER', 'تحويل'), ('OPENING_BALANCE', 'رصيد افتتاحي'), ('ADJUSTMENT', 'تسوية'), ('DEPOSIT', 'إيداع'), ('WITHDRAW', 'سحب')], max_length=20, verbose_name='نوع الحركة')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('CONFIRMED', 'مؤكدة'), ('CANCELLED', 'ملغاة')], default='DRAFT', max_length=20, verbose_name='الحالة')),
                ('transaction_date', models.DateField(verbose_name='تاريخ الحركة')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='المبلغ')),
                ('currency', models.CharField(default='SAR', max_length=10, verbose_name='العملة')),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='مرجع')),
                ('external_reference', models.CharField(blank=True, max_length=255, verbose_name='مرجع خارجي')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('journal_entry_reference', models.CharField(blank=True, help_text='يستخدم لاحقًا بعد ربط الترحيل المحاسبي', max_length=100, verbose_name='مرجع القيد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('destination_account', models.ForeignKey(blank=True, help_text='يستخدم في حالة التحويل', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='treasury.treasuryaccount', verbose_name='الحساب الوجهة')),
                ('treasury_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='treasury.treasuryaccount', verbose_name='الحساب الأساسي')),
            ],
            options={
                'verbose_name': 'حركة خزينة',
                'verbose_name_plural': 'حركات الخزينة',
                'db_table': 'treasury_transactions',
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='treasuryaccount',
            index=models.Index(fields=['code'], name='treasury_ac_code_312259_idx'),
        ),
        migrations.AddIndex(
            model_name='treasuryaccount',
            index=models.Index(fields=['account_type'], name='treasury_ac_account_b10ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='treasuryaccount',
            index=models.Index(fields=['status'], name='treasury_ac_status_b90597_idx'),
        ),
        migrations.AddIndex(
            model_name='treasuryaccount',
            index=models.Index(fields=['currency'], name='treasury_ac_currenc_c11aa2_idx'),
        ),
        migrations.AddIndex(
            model_name='treasuryaccount',
            index=models.Index(fields=['is_default'], name='treasury_ac_is_defa_c7d4e9_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['transaction_number'], name='treasury_tr_transac_bcf486_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['transaction_type'], name='treasury_tr_transac_129d52_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['status'], name='treasury_tr_status_469d83_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['transaction_date'], name='treasury_tr_transac_6d21b2_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['treasury_account'], name='treasury_tr_treasur_df333c_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['destination_account'], name='treasury_tr_destina_14dbe5_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['reference'], name='treasury_tr_referen_928aa5_idx'),
        ),
    ]
