# Generated by Django 5.0.14 on 2026-05-06 10:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_accountingperiod_accountingroutingrule_and_more'),
        ('treasury', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuryaccount',
            name='allow_negative_balance',
            field=models.BooleanField(default=False, verbose_name='السماح برصيد سالب'),
        ),
        migrations.AddField(
            model_name='treasuryaccount',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='معرف التاجر'),
        ),
        migrations.AddField(
            model_name='treasuryaccount',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية'),
        ),
        migrations.AddField(
            model_name='treasuryaccount',
            name='provider_name',
            field=models.CharField(blank=True, help_text='مثل Moyasar أو Tap أو Tamara أو Tabby', max_length=100, verbose_name='اسم مزود الدفع'),
        ),
        migrations.AddField(
            model_name='treasuryaccount',
            name='settlement_days',
            field=models.PositiveIntegerField(default=0, help_text='عدد الأيام المتوقعة لتسوية مبالغ بوابة الدفع', verbose_name='أيام التسوية'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='الرصيد بعد'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='balance_applied',
            field=models.BooleanField(default=False, verbose_name='تم تطبيق أثر الرصيد'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='الرصيد قبل'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='balance_reversed',
            field=models.BooleanField(default=False, verbose_name='تم عكس أثر الرصيد'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_treasury_transactions', to=settings.AUTH_USER_MODEL, verbose_name='ألغيت بواسطة'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التأكيد'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_treasury_transactions', to=settings.AUTH_USER_MODEL, verbose_name='أكدت بواسطة'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_treasury_transactions', to=settings.AUTH_USER_MODEL, verbose_name='أنشئت بواسطة'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='fees_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='مبلغ الرسوم'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_transactions', to='accounting.journalentry', verbose_name='القيد المحاسبي'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='صافي المبلغ'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='party_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='معرف الطرف'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='party_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='اسم الطرف'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='party_type',
            field=models.CharField(blank=True, help_text='مثال: customer, provider, agent, employee', max_length=80, verbose_name='نوع الطرف'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'يدوي'), ('PAYMENT', 'دفعة'), ('INVOICE', 'فاتورة'), ('ORDER', 'طلب'), ('REFUND', 'استرداد'), ('TRANSFER', 'تحويل'), ('GATEWAY', 'بوابة دفع'), ('AGENT_COMMISSION', 'عمولة مندوب'), ('ACCOUNTING', 'محاسبة'), ('OPENING_BALANCE', 'رصيد افتتاحي'), ('ADJUSTMENT', 'تسوية'), ('OTHER', 'أخرى')], default='MANUAL', max_length=40, verbose_name='مصدر الحركة'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='source_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='معرف المصدر'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='source_number',
            field=models.CharField(blank=True, max_length=120, verbose_name='رقم المصدر'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='source_type',
            field=models.CharField(blank=True, help_text='مثال: payment, invoice, order, gateway_transaction', max_length=80, verbose_name='نوع المصدر'),
        ),
        migrations.AlterField(
            model_name='treasuryaccount',
            name='account_type',
            field=models.CharField(choices=[('CASHBOX', 'صندوق نقدي'), ('BANK', 'حساب بنكي'), ('GATEWAY', 'بوابة دفع'), ('WALLET', 'محفظة إلكترونية')], max_length=20, verbose_name='نوع الحساب'),
        ),
        migrations.AlterField(
            model_name='treasuryaccount',
            name='code',
            field=models.CharField(help_text='كود داخلي فريد للصندوق أو البنك أو بوابة الدفع', max_length=50, unique=True, verbose_name='كود الحساب'),
        ),
        migrations.AlterField(
            model_name='treasurytransaction',
            name='journal_entry_reference',
            field=models.CharField(blank=True, help_text='يستخدم للتوافق مع الربط السابق أو عند عدم توفر القيد كعلاقة مباشرة', max_length=100, verbose_name='مرجع القيد'),
        ),
        migrations.AlterField(
            model_name='treasurytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'قبض'), ('EXPENSE', 'صرف'), ('TRANSFER', 'تحويل'), ('OPENING_BALANCE', 'رصيد افتتاحي'), ('ADJUSTMENT', 'تسوية'), ('DEPOSIT', 'إيداع'), ('WITHDRAW', 'سحب'), ('REFUND', 'استرداد'), ('FEE', 'رسوم')], max_length=30, verbose_name='نوع الحركة'),
        ),
        migrations.AddIndex(
            model_name='treasuryaccount',
            index=models.Index(fields=['ledger_account'], name='treasury_ac_ledger__6e733a_idx'),
        ),
        migrations.AddIndex(
            model_name='treasuryaccount',
            index=models.Index(fields=['provider_name'], name='treasury_ac_provide_ac0d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='treasuryaccount',
            index=models.Index(fields=['account_type', 'status'], name='treasury_ac_account_62e2a8_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['source'], name='treasury_tr_source_39b931_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['external_reference'], name='treasury_tr_externa_762a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['source_type'], name='treasury_tr_source__9a56a0_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['source_id'], name='treasury_tr_source__59aa35_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['source_number'], name='treasury_tr_source__7bb323_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['party_type'], name='treasury_tr_party_t_b92739_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['party_id'], name='treasury_tr_party_i_379215_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['journal_entry'], name='treasury_tr_journal_368abf_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['journal_entry_reference'], name='treasury_tr_journal_bfb7f1_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['currency'], name='treasury_tr_currenc_723cba_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['balance_applied'], name='treasury_tr_balance_d49aed_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['balance_reversed'], name='treasury_tr_balance_cb090f_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['status', 'transaction_date'], name='treasury_tr_status_ea5873_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['source', 'source_id'], name='treasury_tr_source_ddd1d8_idx'),
        ),
    ]
