# Generated by Django 5.0.14 on 2026-05-19 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_accountingperiod_accountingroutingrule_and_more'),
        ('treasury', '0002_treasuryaccount_allow_negative_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurytransaction',
            name='counterparty_ledger_account',
            field=models.ForeignKey(blank=True, help_text='الحساب المحاسبي المقابل لحركة القبض أو الصرف أو التسوية. مثال: ذمم العملاء، عهدة مندوب، مستحقات مندوب، دائنون، مصروف، إيراد.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_counterparty_transactions', to='accounting.account', verbose_name='الحساب المحاسبي المقابل'),
        ),
        migrations.AlterField(
            model_name='treasurytransaction',
            name='party_type',
            field=models.CharField(blank=True, help_text='مثال: customer, provider, agent, broker, employee', max_length=80, verbose_name='نوع الطرف'),
        ),
        migrations.AlterField(
            model_name='treasurytransaction',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'يدوي'), ('MANUAL_RECEIPT', 'سند قبض يدوي'), ('MANUAL_PAYMENT', 'سند صرف يدوي'), ('PAYMENT', 'دفعة'), ('INVOICE', 'فاتورة'), ('ORDER', 'طلب'), ('REFUND', 'استرداد'), ('TRANSFER', 'تحويل'), ('GATEWAY', 'بوابة دفع'), ('AGENT_COMMISSION', 'عمولة مندوب'), ('AGENT_COD_COLLECTION', 'تحصيل COD بواسطة مندوب'), ('AGENT_CASH_SETTLEMENT', 'توريد عهدة مندوب'), ('AGENT_EARNING_SETTLEMENT', 'تسوية مستحقات مندوب'), ('BROKER_COMMISSION', 'عمولة وسيط'), ('BROKER_CASH_SETTLEMENT', 'توريد عهدة وسيط'), ('BROKER_EARNING_SETTLEMENT', 'تسوية مستحقات وسيط'), ('ACCOUNTING', 'محاسبة'), ('OPENING_BALANCE', 'رصيد افتتاحي'), ('ADJUSTMENT', 'تسوية'), ('OTHER', 'أخرى')], default='MANUAL', max_length=40, verbose_name='مصدر الحركة'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['counterparty_ledger_account'], name='treasury_tr_counter_a28584_idx'),
        ),
    ]
