# Generated by Django 5.0.14 on 2026-04-21 15:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_reference', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Company Reference')),
                ('company_name', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Company Name')),
                ('recipient_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Recipient Name')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(db_index=True, default='system', max_length=50, verbose_name='Notification Type')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', max_length=20, verbose_name='Severity')),
                ('link', models.CharField(blank=True, default='', max_length=500, verbose_name='Link')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_reference', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Company Reference')),
                ('company_name', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Company Name')),
                ('event_code', models.CharField(db_index=True, max_length=100, verbose_name='Event Code')),
                ('event_group', models.CharField(db_index=True, default='system', max_length=50, verbose_name='Event Group')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', max_length=20, verbose_name='Severity')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('language_code', models.CharField(db_index=True, default='ar', max_length=10, verbose_name='Language Code')),
                ('target_model', models.CharField(blank=True, default='', max_length=100, verbose_name='Target Model')),
                ('target_object_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Target Object ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Title')),
                ('message', models.TextField(blank=True, default='', verbose_name='Message')),
                ('link', models.CharField(blank=True, default='', max_length=500, verbose_name='Link')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='Context')),
                ('source', models.CharField(blank=True, default='', max_length=100, verbose_name='Source')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notification_events', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_notification_events', to=settings.AUTH_USER_MODEL, verbose_name='Target User')),
            ],
            options={
                'verbose_name': 'Notification Event',
                'verbose_name_plural': 'Notification Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_reference', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Company Reference')),
                ('company_name', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Company Name')),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('push', 'Push')], db_index=True, max_length=20, verbose_name='Channel')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('retrying', 'Retrying'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('destination', models.CharField(blank=True, default='', max_length=255, verbose_name='Destination')),
                ('subject', models.CharField(blank=True, default='', max_length=255, verbose_name='Subject')),
                ('rendered_message', models.TextField(blank=True, default='', verbose_name='Rendered Message')),
                ('template_key', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='Template Key')),
                ('language_code', models.CharField(db_index=True, default='ar', max_length=10, verbose_name='Language Code')),
                ('provider_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Provider Name')),
                ('provider_message_id', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Provider Message ID')),
                ('provider_response', models.JSONField(blank=True, default=dict, verbose_name='Provider Response')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error Message')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Attempts')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='Max Attempts')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Attempt At')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='notification_center.notification', verbose_name='Notification')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notification_center.notificationevent', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Notification Delivery',
                'verbose_name_plural': 'Notification Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notification_center.notificationevent', verbose_name='Event'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['event_code', '-created_at'], name='notificatio_event_c_5112be_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['event_group', '-created_at'], name='notificatio_event_g_892b45_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['company_reference', '-created_at'], name='notificatio_company_4338fc_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['target_user', '-created_at'], name='notificatio_target__f32efc_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['status', '-created_at'], name='notificatio_status_80e75d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['severity', '-created_at'], name='notificatio_severit_5d6103_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['language_code', '-created_at'], name='notificatio_languag_7d8d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['event', 'channel'], name='notificatio_event_i_7e9394_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['recipient', 'channel'], name='notificatio_recipie_74b0b6_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['status', 'channel'], name='notificatio_status_10b042_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['company_reference', '-created_at'], name='notificatio_company_030c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['provider_message_id'], name='notificatio_provide_3f258d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['template_key', 'language_code'], name='notificatio_templat_5caee2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_f28ac0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_c78193_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['company_reference', '-created_at'], name='notificatio_company_748a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'severity'], name='notificatio_notific_9983cf_idx'),
        ),
    ]
