# Generated by Django 5.0.14 on 2026-04-21 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(db_index=True, default='SYSTEM', help_text='SYSTEM / COMPANY / OTHER', max_length=30, verbose_name='نوع النطاق')),
                ('company_reference', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='مرجع الجهة / الشركة')),
                ('company_name', models.CharField(blank=True, default='', max_length=255, verbose_name='اسم الجهة / الشركة')),
                ('module', models.CharField(help_text='مثال: customers, invoices, whatsapp, payments', max_length=100, verbose_name='الوحدة')),
                ('action', models.CharField(help_text='مثال: create, update, delete, sync, login', max_length=100, verbose_name='الإجراء')),
                ('event_code', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='رمز الحدث')),
                ('severity', models.CharField(choices=[('info', 'معلومة'), ('warning', 'تحذير'), ('error', 'خطأ'), ('critical', 'حرج')], db_index=True, default='info', max_length=20, verbose_name='مستوى الخطورة')),
                ('message', models.TextField(help_text='وصف الحدث الذي حصل داخل النظام', verbose_name='الرسالة')),
                ('path', models.CharField(blank=True, default='', max_length=500, verbose_name='المسار')),
                ('method', models.CharField(blank=True, default='', max_length=20, verbose_name='الطريقة')),
                ('status_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='رمز الاستجابة')),
                ('ip_address', models.CharField(blank=True, default='', max_length=100, verbose_name='عنوان IP')),
                ('extra_data', models.JSONField(blank=True, help_text='تخزين أي تفاصيل إضافية (مثل قبل/بعد التعديل)', null=True, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت الإنشاء')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المنفّذ')),
            ],
            options={
                'verbose_name': 'سجل نظام',
                'verbose_name_plural': 'سجلات النظام',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['scope_type', 'created_at'], name='system_log__scope_t_831833_idx'), models.Index(fields=['company_reference', 'created_at'], name='system_log__company_3af841_idx'), models.Index(fields=['module', 'created_at'], name='system_log__module_07441d_idx'), models.Index(fields=['severity', 'created_at'], name='system_log__severit_d8ee0e_idx'), models.Index(fields=['event_code', 'created_at'], name='system_log__event_c_ad9332_idx')],
            },
        ),
    ]
