# Generated by Django 5.0.14 on 2026-04-28 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentcommission_agent_commi_approve_6f91c7_idx_and_more'),
        ('contracts', '0002_contract_system_commission_percentage_and_more'),
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0002_productserviceitem_product_allow_agent_sale_and_more'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Optional agent linked to this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='agents.agent', verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='order',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Optional contract used to price/fulfill this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='contracts.contract', verbose_name='Contract'),
        ),
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Optional provider/center selected for this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='providers.provider', verbose_name='Provider / Center'),
        ),
        migrations.AlterField(
            model_name='order',
            name='issue_reference',
            field=models.CharField(blank=True, help_text='Used for card/program/service issue reference.', max_length=100, verbose_name='Issue Reference'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['provider', 'created_at'], name='orders_orde_provide_cf0c69_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['contract', 'created_at'], name='orders_orde_contrac_663e40_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['agent', 'created_at'], name='orders_orde_agent_i_9fd8ea_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_1de1d7_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['to_status', 'created_at'], name='orders_orde_to_stat_377133_idx'),
        ),
    ]
