# Generated by Django 5.0.14 on 2026-05-11 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentcommission_agent_commi_approve_6f91c7_idx_and_more'),
        ('contracts', '0002_contract_system_commission_percentage_and_more'),
        ('customers', '0002_customerloginotp_customer_last_login_at_and_more'),
        ('orders', '0002_order_agent_order_contract_order_provider_and_more'),
        ('products', '0004_alter_product_slug'),
        ('providers', '0003_providerdocument_provider_commercial_registration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ends_at',
            field=models.DateField(blank=True, db_index=True, help_text='End date for card/program/subscription validity.', null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_kind',
            field=models.CharField(choices=[('general', 'General'), ('card', 'Card'), ('program', 'Program'), ('service', 'Service'), ('subscription', 'Subscription')], db_index=True, default='general', help_text='Business type of this order: card, program, service, subscription, or general.', max_length=30, verbose_name='Order Kind'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('none', 'None'), ('cash', 'Cash'), ('cash_on_delivery', 'Cash on Delivery'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('payment_gateway', 'Payment Gateway'), ('wallet', 'Wallet'), ('tamara', 'Tamara'), ('tabby', 'Tabby'), ('other', 'Other')], db_index=True, default='none', help_text='Selected payment method at order creation time.', max_length=30, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Optional external or internal payment reference.', max_length=120, verbose_name='Payment Reference'),
        ),
        migrations.AddField(
            model_name='order',
            name='referral_code_used',
            field=models.CharField(blank=True, db_index=True, help_text='Agent/referral/employee code used when creating the order.', max_length=100, verbose_name='Referral Code Used'),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Optional appointment/execution datetime for one-time services.', null=True, verbose_name='Scheduled At'),
        ),
        migrations.AddField(
            model_name='order',
            name='starts_at',
            field=models.DateField(blank=True, db_index=True, help_text='Start date for card/program/subscription validity.', null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent linked to this order. Resolved automatically for agent users.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='agents.agent', verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Resolved contract used to price/fulfill this order when applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='contracts.contract', verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Resolved provider/center for this order when applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='providers.provider', verbose_name='Provider / Center'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_kind'], name='orders_orde_order_k_ae6cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_method'], name='orders_orde_payment_63e120_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['starts_at', 'ends_at'], name='orders_orde_starts__5bd15e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['scheduled_at'], name='orders_orde_schedul_4e680a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['referral_code_used'], name='orders_orde_referra_cef9c3_idx'),
        ),
    ]
