# Generated by Django 5.0.14 on 2026-05-13 12:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentcommission_agent_commi_approve_6f91c7_idx_and_more'),
        ('contracts', '0002_contract_system_commission_percentage_and_more'),
        ('customers', '0002_customerloginotp_customer_last_login_at_and_more'),
        ('orders', '0003_order_ends_at_order_order_kind_order_payment_method_and_more'),
        ('products', '0004_alter_product_slug'),
        ('providers', '0003_providerdocument_provider_commercial_registration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('confirmed', 'Confirmed'), ('card_printed', 'Card Printed'), ('card_ready', 'Card Ready'), ('delivery_assigned', 'Delivery Assigned'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cash_collected', 'Cash Collected'), ('payment_updated', 'Payment Updated'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('note', 'Note'), ('system', 'System')], db_index=True, default='updated', max_length=40, verbose_name='Event Type')),
                ('from_status', models.CharField(blank=True, max_length=30, verbose_name='From Order Status')),
                ('to_status', models.CharField(blank=True, max_length=30, verbose_name='To Order Status')),
                ('from_payment_status', models.CharField(blank=True, max_length=30, verbose_name='From Payment Status')),
                ('to_payment_status', models.CharField(blank=True, max_length=30, verbose_name='To Payment Status')),
                ('from_fulfillment_status', models.CharField(blank=True, max_length=30, verbose_name='From Fulfillment Status')),
                ('to_fulfillment_status', models.CharField(blank=True, max_length=30, verbose_name='To Fulfillment Status')),
                ('title', models.CharField(max_length=180, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Amount')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Order Timeline',
                'verbose_name_plural': 'Order Timeline',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_for_delivery_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Assigned for Delivery At'),
        ),
        migrations.AddField(
            model_name='order',
            name='card_printed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Card Printed At'),
        ),
        migrations.AddField(
            model_name='order',
            name='card_ready_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Card Ready At'),
        ),
        migrations.AddField(
            model_name='order',
            name='cash_collected_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount collected by delivery agent for COD orders.', max_digits=12, verbose_name='Cash Collected Amount'),
        ),
        migrations.AddField(
            model_name='order',
            name='cash_collected_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Cash Collected At'),
        ),
        migrations.AddField(
            model_name='order',
            name='cash_collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_cash_collected', to=settings.AUTH_USER_MODEL, verbose_name='Cash Collected By'),
        ),
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Completed At'),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Confirmed At'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Delivered At'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_agent',
            field=models.ForeignKey(blank=True, help_text='Agent assigned to deliver the card/order and collect COD amount when applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='agents.agent', verbose_name='Delivery Agent'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_notes',
            field=models.TextField(blank=True, verbose_name='Delivery Notes'),
        ),
        migrations.AddField(
            model_name='order',
            name='out_for_delivery_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Out for Delivery At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Sales/referral agent linked to this order. Resolved automatically for agent users or referral codes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='agents.agent', verbose_name='Sales Agent'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('issued', 'Issued'), ('ready', 'Ready'), ('assigned', 'Assigned'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('returned', 'Returned')], db_index=True, default='not_started', max_length=30, verbose_name='Fulfillment Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('cod_pending', 'Cash on Delivery Pending'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='unpaid', max_length=30, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('card_ready', 'Card Ready'), ('assigned_for_delivery', 'Assigned for Delivery'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=30, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='from_status',
            field=models.CharField(blank=True, max_length=30, verbose_name='From Status'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='to_status',
            field=models.CharField(max_length=30, verbose_name='To Status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'fulfillment_status'], name='orders_orde_status_3c784b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_agent', 'created_at'], name='orders_orde_deliver_af5a77_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['confirmed_at'], name='orders_orde_confirm_75fecf_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['card_ready_at'], name='orders_orde_card_re_e015c9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['assigned_for_delivery_at'], name='orders_orde_assigne_5ca80f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['out_for_delivery_at'], name='orders_orde_out_for_db3041_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivered_at'], name='orders_orde_deliver_1355ff_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['cash_collected_at'], name='orders_orde_cash_co_6ee434_idx'),
        ),
        migrations.AddField(
            model_name='ordertimeline',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_timeline_events', to=settings.AUTH_USER_MODEL, verbose_name='Actor'),
        ),
        migrations.AddField(
            model_name='ordertimeline',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_timeline_sales_events', to='agents.agent', verbose_name='Sales Agent'),
        ),
        migrations.AddField(
            model_name='ordertimeline',
            name='delivery_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_timeline_delivery_events', to='agents.agent', verbose_name='Delivery Agent'),
        ),
        migrations.AddField(
            model_name='ordertimeline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='orders.order', verbose_name='Order'),
        ),
        migrations.AddIndex(
            model_name='ordertimeline',
            index=models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_a5a9a4_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertimeline',
            index=models.Index(fields=['event_type', 'created_at'], name='orders_orde_event_t_8184cc_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertimeline',
            index=models.Index(fields=['to_status', 'created_at'], name='orders_orde_to_stat_edd2e7_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertimeline',
            index=models.Index(fields=['to_payment_status', 'created_at'], name='orders_orde_to_paym_b4e82c_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertimeline',
            index=models.Index(fields=['to_fulfillment_status', 'created_at'], name='orders_orde_to_fulf_7ab267_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertimeline',
            index=models.Index(fields=['actor', 'created_at'], name='orders_orde_actor_i_180dae_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertimeline',
            index=models.Index(fields=['agent', 'created_at'], name='orders_orde_agent_i_b678b0_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertimeline',
            index=models.Index(fields=['delivery_agent', 'created_at'], name='orders_orde_deliver_37c1fa_idx'),
        ),
    ]
