# Generated by Django 5.0.14 on 2026-05-14 13:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_created_by_agent_updated_by_agent_user_and_more'),
        ('contracts', '0003_alter_contractproduct_options_and_more'),
        ('customers', '0002_customerloginotp_customer_last_login_at_and_more'),
        ('orders', '0004_ordertimeline_order_assigned_for_delivery_at_and_more'),
        ('products', '0005_product_discount_percentage_product_has_duration_and_more'),
        ('providers', '0003_providerdocument_provider_commercial_registration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contract_product',
            field=models.ForeignKey(blank=True, help_text='Selected provider offer used to price this order when coming from landing/offers/checkout.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='contracts.contractproduct', verbose_name='Contract Product Offer'),
        ),
        migrations.AddField(
            model_name='order',
            name='offer_badge',
            field=models.CharField(blank=True, max_length=100, verbose_name='Offer Badge Snapshot'),
        ),
        migrations.AddField(
            model_name='order',
            name='offer_source',
            field=models.CharField(choices=[('none', 'None'), ('product', 'Product'), ('contract_product', 'Contract Product'), ('manual', 'Manual')], db_index=True, default='none', help_text='Where the order pricing snapshot came from.', max_length=30, verbose_name='Offer Source'),
        ),
        migrations.AddField(
            model_name='order',
            name='offer_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Offer Title Snapshot'),
        ),
        migrations.AddField(
            model_name='order',
            name='unit_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Snapshot discount percentage used for this order.', max_digits=5, verbose_name='Unit Discount Percentage'),
        ),
        migrations.AddField(
            model_name='order',
            name='unit_price_before_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Snapshot of original unit price before discount.', max_digits=12, verbose_name='Unit Price Before Discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_type',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Product Type Snapshot'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('whatsapp', 'WhatsApp'), ('agent', 'Agent'), ('admin', 'Admin'), ('mobile_app', 'Mobile App'), ('landing', 'Landing'), ('checkout', 'Checkout'), ('other', 'Other')], db_index=True, default='admin', max_length=20, verbose_name='Order Source'),
        ),
        migrations.AlterField(
            model_name='order',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final unit price after discount.', max_digits=12, verbose_name='Unit Price'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['offer_source'], name='orders_orde_offer_s_79285d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['contract_product', 'created_at'], name='orders_orde_contrac_9b59f1_idx'),
        ),
    ]
