# Generated by Django 5.0.14 on 2026-04-21 14:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('TAMARA', 'Tamara'), ('TAP', 'Tap')], max_length=20, unique=True, verbose_name='مزود البوابة')),
                ('display_name', models.CharField(blank=True, default='', max_length=150, verbose_name='الاسم الظاهر')),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20, verbose_name='البيئة')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='مفعلة')),
                ('is_default', models.BooleanField(default=False, help_text='تستخدم لاحقًا عند وجود أكثر من بوابة مفعلة.', verbose_name='الافتراضية')),
                ('base_url', models.URLField(blank=True, default='', verbose_name='Base URL')),
                ('timeout_seconds', models.PositiveIntegerField(default=30, verbose_name='مهلة الطلب بالثواني')),
                ('verify_webhook', models.BooleanField(default=True, verbose_name='التحقق من webhook')),
                ('api_token', models.TextField(blank=True, default='', verbose_name='API Token')),
                ('secret_key', models.TextField(blank=True, default='', verbose_name='Secret Key')),
                ('public_key', models.TextField(blank=True, default='', verbose_name='Public Key')),
                ('merchant_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Merchant ID')),
                ('source_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Source ID')),
                ('notification_token', models.TextField(blank=True, default='', verbose_name='Notification Token')),
                ('webhook_secret', models.TextField(blank=True, default='', verbose_name='Webhook Secret')),
                ('merchant_callback_url', models.URLField(blank=True, default='', verbose_name='Merchant Callback URL')),
                ('extra_config', models.JSONField(blank=True, default=dict, verbose_name='إعدادات إضافية')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'Payment Gateway Config',
                'verbose_name_plural': 'Payment Gateway Configs',
                'ordering': ['provider'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('TAMARA', 'Tamara'), ('TAP', 'Tap')], db_index=True, max_length=20, verbose_name='مزود البوابة')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INITIATED', 'Initiated'), ('PROCESSING', 'Processing'), ('REQUIRES_ACTION', 'Requires Action'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=30, verbose_name='الحالة المحلية')),
                ('gateway_status', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='حالة البوابة')),
                ('payment_method', models.CharField(blank=True, default='', max_length=50, verbose_name='طريقة الدفع')),
                ('currency', models.CharField(default='SAR', max_length=10, verbose_name='العملة')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='المبلغ')),
                ('local_reference_type', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='نوع المرجع المحلي')),
                ('local_reference_id', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='رقم المرجع المحلي')),
                ('local_reference', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='المرجع المحلي')),
                ('customer_name', models.CharField(blank=True, default='', max_length=255, verbose_name='اسم العميل')),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='بريد العميل')),
                ('customer_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='جوال العميل')),
                ('remote_transaction_id', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Remote Transaction ID')),
                ('remote_order_id', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Remote Order ID')),
                ('remote_checkout_id', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Remote Checkout ID')),
                ('gateway_reference', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Gateway Reference')),
                ('payment_url', models.URLField(blank=True, default='', verbose_name='رابط الدفع')),
                ('redirect_url', models.URLField(blank=True, default='', verbose_name='رابط الإرجاع')),
                ('is_webhook_verified', models.BooleanField(default=False, verbose_name='تم التحقق من webhook')),
                ('last_webhook_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر webhook')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ السداد')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload الطلب')),
                ('response_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload الاستجابة')),
                ('latest_webhook_payload', models.JSONField(blank=True, default=dict, verbose_name='آخر Webhook Payload')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'Payment Gateway Transaction',
                'verbose_name_plural': 'Payment Gateway Transactions',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['provider', 'status'], name='payment_gat_provide_441766_idx'), models.Index(fields=['provider', 'remote_transaction_id'], name='payment_gat_provide_c0cd12_idx'), models.Index(fields=['provider', 'remote_order_id'], name='payment_gat_provide_df4bca_idx'), models.Index(fields=['provider', 'local_reference_type', 'local_reference_id'], name='payment_gat_provide_692454_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('TAMARA', 'Tamara'), ('TAP', 'Tap')], db_index=True, max_length=20, verbose_name='مزود البوابة')),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], db_index=True, default='RECEIVED', max_length=20, verbose_name='حالة السجل')),
                ('event_type', models.CharField(blank=True, db_index=True, default='', max_length=150, verbose_name='نوع الحدث')),
                ('signature_valid', models.BooleanField(default=False, verbose_name='التوقيع صحيح')),
                ('remote_transaction_id', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Remote Transaction ID')),
                ('remote_order_id', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Remote Order ID')),
                ('remote_checkout_id', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Remote Checkout ID')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='Headers')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('processing_result', models.JSONField(blank=True, default=dict, verbose_name='نتيجة المعالجة')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='رسالة الخطأ')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت الاستلام')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت المعالجة')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='payment_gateways.paymentgatewaytransaction', verbose_name='العملية المرتبطة')),
            ],
            options={
                'verbose_name': 'Payment Gateway Webhook Log',
                'verbose_name_plural': 'Payment Gateway Webhook Logs',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['provider', 'status'], name='payment_gat_provide_eeb54b_idx'), models.Index(fields=['provider', 'event_type'], name='payment_gat_provide_29cb03_idx'), models.Index(fields=['provider', 'remote_transaction_id'], name='payment_gat_provide_71e635_idx'), models.Index(fields=['provider', 'remote_order_id'], name='payment_gat_provide_41af96_idx')],
            },
        ),
    ]
