# Generated by Django 5.0.14 on 2026-04-18 19:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الحساب')),
                ('code', models.CharField(help_text='كود فريد للحساب داخل دليل الحسابات', max_length=50, unique=True, verbose_name='كود الحساب')),
                ('account_type', models.CharField(choices=[('ASSET', 'أصل'), ('LIABILITY', 'خصم'), ('EQUITY', 'حقوق ملكية'), ('REVENUE', 'إيراد'), ('EXPENSE', 'مصروف')], max_length=20, verbose_name='نوع الحساب')),
                ('nature', models.CharField(choices=[('DEBIT', 'مدين'), ('CREDIT', 'دائن')], help_text='الطبيعة الافتراضية للحساب: مدين أو دائن', max_length=10, verbose_name='طبيعة الحساب')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='المستوى')),
                ('is_group', models.BooleanField(default=False, help_text='إذا كان مفعّلًا فهذا الحساب للتجميع وليس للترحيل المباشر', verbose_name='حساب تجميعي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account', verbose_name='الحساب الأب')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'دليل الحسابات',
                'db_table': 'accounting_accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(help_text='رقم مرجعي داخلي فريد للقيد', max_length=100, unique=True, verbose_name='رقم القيد')),
                ('entry_date', models.DateField(verbose_name='تاريخ القيد')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحل'), ('CANCELLED', 'ملغي')], default='DRAFT', max_length=20, verbose_name='الحالة')),
                ('posting_source', models.CharField(choices=[('MANUAL', 'يدوي'), ('ORDER', 'طلب'), ('PAYMENT', 'دفعة'), ('INVOICE', 'فاتورة'), ('REFUND', 'استرداد'), ('ADJUSTMENT', 'تسوية'), ('OTHER', 'أخرى')], default='MANUAL', max_length=20, verbose_name='مصدر القيد')),
                ('reference', models.CharField(blank=True, help_text='مثل رقم فاتورة أو دفعة أو طلب', max_length=255, verbose_name='مرجع')),
                ('external_reference', models.CharField(blank=True, max_length=255, verbose_name='مرجع خارجي')),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='إجمالي المدين')),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='إجمالي الدائن')),
                ('currency', models.CharField(default='SAR', max_length=10, verbose_name='العملة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الترحيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'قيد يومية',
                'verbose_name_plural': 'القيود اليومية',
                'db_table': 'accounting_journal_entries',
                'ordering': ['-entry_date', '-id'],
                'indexes': [models.Index(fields=['entry_number'], name='accounting__entry_n_6a4196_idx'), models.Index(fields=['entry_date'], name='accounting__entry_d_27b3a0_idx'), models.Index(fields=['status'], name='accounting__status_037e0d_idx'), models.Index(fields=['posting_source'], name='accounting__posting_9ce266_idx'), models.Index(fields=['reference'], name='accounting__referen_26cfca_idx')],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='مدين')),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='دائن')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.account', verbose_name='الحساب')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry', verbose_name='القيد')),
            ],
            options={
                'verbose_name': 'سطر قيد',
                'verbose_name_plural': 'أسطر القيود',
                'db_table': 'accounting_journal_entry_lines',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['code'], name='accounting__code_4dfc77_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_type'], name='accounting__account_96248c_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['nature'], name='accounting__nature_5b92e2_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['parent'], name='accounting__parent__cb267e_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_group'], name='accounting__is_grou_aaf020_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_active'], name='accounting__is_acti_8b7038_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['journal_entry'], name='accounting__journal_72bf4a_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['account'], name='accounting__account_cbc3e2_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['sort_order'], name='accounting__sort_or_392e02_idx'),
        ),
    ]
