# Generated by Django 5.0.14 on 2026-04-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='posting_source',
            field=models.CharField(choices=[('MANUAL', 'يدوي'), ('OPENING_BALANCE', 'رصيد افتتاحي'), ('ORDER', 'طلب'), ('INVOICE', 'فاتورة'), ('PAYMENT', 'دفعة'), ('REFUND', 'استرداد'), ('AGENT_COMMISSION', 'عمولة مندوب'), ('TREASURY', 'خزينة'), ('ADJUSTMENT', 'تسوية'), ('OTHER', 'أخرى')], default='MANUAL', max_length=30, verbose_name='مصدر القيد'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_type', 'is_active'], name='accounting__account_aa34fc_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['parent', 'is_active'], name='accounting__parent__2641b3_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['external_reference'], name='accounting__externa_bcefbe_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['status', 'entry_date'], name='accounting__status_12b9cf_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['posting_source', 'reference'], name='accounting__posting_07b5b5_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['journal_entry', 'sort_order'], name='accounting__journal_40cce9_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['account', 'created_at'], name='accounting__account_bae40a_idx'),
        ),
    ]
