# Generated by Django 5.0.14 on 2026-05-06 10:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_journalentry_posting_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفترة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('OPEN', 'مفتوحة'), ('CLOSED', 'مغلقة'), ('LOCKED', 'مقفلة')], default='OPEN', max_length=20, verbose_name='الحالة')),
                ('is_adjustment_period', models.BooleanField(default=False, verbose_name='فترة تسويات')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'فترة محاسبية',
                'verbose_name_plural': 'الفترات المحاسبية',
                'db_table': 'accounting_periods',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='AccountingRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('SALES_INVOICE', 'فاتورة مبيعات'), ('PURCHASE_INVOICE', 'فاتورة مشتريات'), ('PAYMENT_RECEIPT', 'قبض دفعة'), ('PAYMENT_REFUND', 'استرداد دفعة'), ('TREASURY_INCOME', 'قبض خزينة'), ('TREASURY_EXPENSE', 'صرف خزينة'), ('TREASURY_TRANSFER', 'تحويل خزينة'), ('EXPENSE', 'مصروف'), ('INCOME', 'إيراد'), ('AGENT_COMMISSION', 'عمولة مندوب'), ('TAX_SETTLEMENT', 'تسوية ضريبية'), ('OPENING_BALANCE', 'رصيد افتتاحي'), ('OTHER', 'أخرى')], max_length=50, verbose_name='مصدر العملية')),
                ('purpose', models.CharField(choices=[('ACCOUNTS_RECEIVABLE', 'ذمم العملاء'), ('ACCOUNTS_PAYABLE', 'ذمم الموردين'), ('CASH', 'الصندوق'), ('BANK', 'البنك'), ('SALES_REVENUE', 'إيرادات المبيعات'), ('OTHER_REVENUE', 'إيرادات أخرى'), ('OUTPUT_VAT', 'ضريبة مخرجات'), ('INPUT_VAT', 'ضريبة مدخلات'), ('VAT_PAYABLE', 'ضريبة مستحقة'), ('DISCOUNT_ALLOWED', 'خصم مسموح'), ('DISCOUNT_EARNED', 'خصم مكتسب'), ('COST_OF_SALES', 'تكلفة المبيعات'), ('EXPENSE', 'مصروف'), ('AGENT_COMMISSION_EXPENSE', 'مصروف عمولة مندوب'), ('AGENT_COMMISSION_PAYABLE', 'مستحقات مندوب'), ('GATEWAY_FEES', 'رسوم بوابة دفع'), ('ROUNDING', 'فروقات تقريب'), ('OPENING_EQUITY', 'حقوق أرصدة افتتاحية'), ('SUSPENSE', 'حساب معلق'), ('OTHER', 'أخرى')], max_length=80, verbose_name='الغرض المحاسبي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='الأولوية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'قاعدة توجيه محاسبي',
                'verbose_name_plural': 'قواعد التوجيه المحاسبي',
                'db_table': 'accounting_routing_rules',
                'ordering': ['source', 'purpose', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='AccountingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_currency', models.CharField(default='SAR', max_length=10, verbose_name='العملة الافتراضية')),
                ('auto_post_invoices', models.BooleanField(default=True, verbose_name='ترحيل الفواتير تلقائيًا')),
                ('auto_post_payments', models.BooleanField(default=True, verbose_name='ترحيل المدفوعات تلقائيًا')),
                ('auto_post_treasury', models.BooleanField(default=False, verbose_name='ترحيل الخزينة تلقائيًا')),
                ('require_period_for_posting', models.BooleanField(default=False, verbose_name='إلزام الفترة عند الترحيل')),
                ('allow_posting_without_cost_center', models.BooleanField(default=True, verbose_name='السماح بالترحيل بدون مركز تكلفة')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات المحاسبة',
                'verbose_name_plural': 'إعدادات المحاسبة',
                'db_table': 'accounting_settings',
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم مركز التكلفة')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='اسم مركز التكلفة بالإنجليزية')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود مركز التكلفة')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='المستوى')),
                ('is_group', models.BooleanField(default=False, verbose_name='مركز تجميعي')),
                ('status', models.CharField(choices=[('ACTIVE', 'نشط'), ('INACTIVE', 'غير نشط')], default='ACTIVE', max_length=20, verbose_name='الحالة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'مركز تكلفة',
                'verbose_name_plural': 'مراكز التكلفة',
                'db_table': 'accounting_cost_centers',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم السنة المالية')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('OPEN', 'مفتوحة'), ('CLOSED', 'مغلقة'), ('ARCHIVED', 'مؤرشفة')], default='OPEN', max_length=20, verbose_name='الحالة')),
                ('is_current', models.BooleanField(default=False, verbose_name='السنة الحالية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'سنة مالية',
                'verbose_name_plural': 'السنوات المالية',
                'db_table': 'accounting_fiscal_years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الضريبة')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الضريبة')),
                ('tax_type', models.CharField(choices=[('VAT', 'ضريبة القيمة المضافة'), ('WITHHOLDING', 'ضريبة استقطاع'), ('ZAKAT', 'زكاة'), ('OTHER', 'أخرى')], default='VAT', max_length=20, verbose_name='نوع الضريبة')),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=7, verbose_name='النسبة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'ضريبة',
                'verbose_name_plural': 'الضرائب',
                'db_table': 'accounting_tax_rates',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TaxTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('OUTPUT', 'ضريبة مبيعات'), ('INPUT', 'ضريبة مشتريات'), ('SETTLEMENT', 'تسوية ضريبية')], max_length=20, verbose_name='اتجاه الضريبة')),
                ('transaction_date', models.DateField(verbose_name='تاريخ الحركة')),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='المبلغ الخاضع للضريبة')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='مبلغ الضريبة')),
                ('currency', models.CharField(default='SAR', max_length=10, verbose_name='العملة')),
                ('source_type', models.CharField(blank=True, max_length=80, verbose_name='نوع المصدر')),
                ('source_id', models.CharField(blank=True, max_length=80, verbose_name='معرف المصدر')),
                ('source_number', models.CharField(blank=True, max_length=120, verbose_name='رقم المصدر')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'حركة ضريبية',
                'verbose_name_plural': 'الحركات الضريبية',
                'db_table': 'accounting_tax_transactions',
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='allow_manual_posting',
            field=models.BooleanField(default=True, verbose_name='يسمح بالترحيل اليدوي'),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(default='SAR', max_length=10, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_system',
            field=models.BooleanField(default=False, help_text='الحسابات النظامية تستخدم في التوجيه المحاسبي ولا يفضل حذفها.', verbose_name='حساب نظامي'),
        ),
        migrations.AddField(
            model_name='account',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية'),
        ),
        migrations.AddField(
            model_name='account',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='اسم الحساب بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='account',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='الرصيد الافتتاحي'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='ألغي بواسطة'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_auto_posted',
            field=models.BooleanField(default=False, verbose_name='مرحل آليًا'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='رحل بواسطة'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_entries', to='accounting.journalentry', verbose_name='قيد عكسي لـ'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ العكس'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversed_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_reversed_entries', to='accounting.journalentry', verbose_name='القيد العكسي'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='معرف المصدر'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_number',
            field=models.CharField(blank=True, max_length=120, verbose_name='رقم المصدر'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(blank=True, help_text='مثال: invoice, payment, treasury_transaction', max_length=80, verbose_name='نوع المصدر'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='party_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='معرف الطرف'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='party_type',
            field=models.CharField(blank=True, help_text='مثال: customer, provider, agent, employee', max_length=80, verbose_name='نوع الطرف'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='source_line_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='معرف سطر المصدر'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='مبلغ الضريبة'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='posting_source',
            field=models.CharField(choices=[('MANUAL', 'يدوي'), ('OPENING_BALANCE', 'رصيد افتتاحي'), ('ORDER', 'طلب'), ('INVOICE', 'فاتورة'), ('PAYMENT', 'دفعة'), ('REFUND', 'استرداد'), ('AGENT_COMMISSION', 'عمولة مندوب'), ('TREASURY', 'خزينة'), ('TREASURY_TRANSFER', 'تحويل خزينة'), ('EXPENSE', 'مصروف'), ('INCOME', 'إيراد'), ('TAX', 'ضريبة'), ('ADJUSTMENT', 'تسوية'), ('SYSTEM', 'نظام'), ('OTHER', 'أخرى')], default='MANUAL', max_length=30, verbose_name='مصدر القيد'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحل'), ('CANCELLED', 'ملغي'), ('REVERSED', 'معكوس')], default='DRAFT', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['level'], name='accounting__level_265940_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_system'], name='accounting__is_syst_0e120e_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['currency'], name='accounting__currenc_8fce74_idx'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.accountingperiod', verbose_name='الفترة المحاسبية'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['period'], name='accounting__period__7c4b66_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_type'], name='accounting__source__741cc8_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_id'], name='accounting__source__0c20f6_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_number'], name='accounting__source__5ed473_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['currency'], name='accounting__currenc_748cf5_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['is_auto_posted'], name='accounting__is_auto_bce6e4_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_type', 'source_id'], name='accounting__source__fb3a7c_idx'),
        ),
        migrations.AddField(
            model_name='accountingroutingrule',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routing_rules', to='accounting.account', verbose_name='الحساب'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.costcenter', verbose_name='مركز التكلفة الأب'),
        ),
        migrations.AddField(
            model_name='accountingroutingrule',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_rules', to='accounting.costcenter', verbose_name='مركز التكلفة'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='accounting.costcenter', verbose_name='مركز التكلفة'),
        ),
        migrations.AddIndex(
            model_name='fiscalyear',
            index=models.Index(fields=['start_date'], name='accounting__start_d_f5b4fd_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalyear',
            index=models.Index(fields=['end_date'], name='accounting__end_dat_613ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalyear',
            index=models.Index(fields=['status'], name='accounting__status_f8c652_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalyear',
            index=models.Index(fields=['is_current'], name='accounting__is_curr_b15bf7_idx'),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='accounting.fiscalyear', verbose_name='السنة المالية'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='purchase_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_tax_rates', to='accounting.account', verbose_name='حساب ضريبة المشتريات'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='sales_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_tax_rates', to='accounting.account', verbose_name='حساب ضريبة المبيعات'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='default_tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_in_settings', to='accounting.taxrate', verbose_name='الضريبة الافتراضية'),
        ),
        migrations.AddField(
            model_name='accountingroutingrule',
            name='tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_rules', to='accounting.taxrate', verbose_name='الضريبة'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='accounting.taxrate', verbose_name='الضريبة'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['cost_center'], name='accounting__cost_ce_f9ca61_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['tax_rate'], name='accounting__tax_rat_6a8cad_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['party_type'], name='accounting__party_t_427076_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['party_id'], name='accounting__party_i_a2ac13_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['source_line_id'], name='accounting__source__067ea9_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['cost_center', 'created_at'], name='accounting__cost_ce_86bfe4_idx'),
        ),
        migrations.AddField(
            model_name='taxtransaction',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_transactions', to='accounting.journalentry', verbose_name='القيد المحاسبي'),
        ),
        migrations.AddField(
            model_name='taxtransaction',
            name='journal_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_transactions', to='accounting.journalentryline', verbose_name='سطر القيد'),
        ),
        migrations.AddField(
            model_name='taxtransaction',
            name='tax_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_transactions', to='accounting.taxrate', verbose_name='الضريبة'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['code'], name='accounting__code_7e788e_idx'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['parent'], name='accounting__parent__d7fb92_idx'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['level'], name='accounting__level_37b3c0_idx'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['is_group'], name='accounting__is_grou_eb05bf_idx'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['status'], name='accounting__status_9a89e0_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['fiscal_year'], name='accounting__fiscal__d50d21_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['start_date'], name='accounting__start_d_3c3769_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['end_date'], name='accounting__end_dat_959ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['status'], name='accounting__status_89de41_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['is_adjustment_period'], name='accounting__is_adju_6f37ea_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['fiscal_year', 'status'], name='accounting__fiscal__c78858_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['code'], name='accounting__code_27ed5a_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['tax_type'], name='accounting__tax_typ_6a5135_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['is_active'], name='accounting__is_acti_dfa486_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['is_default'], name='accounting__is_defa_72ff4a_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingroutingrule',
            index=models.Index(fields=['source'], name='accounting__source_e209d2_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingroutingrule',
            index=models.Index(fields=['purpose'], name='accounting__purpose_bcca7f_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingroutingrule',
            index=models.Index(fields=['is_active'], name='accounting__is_acti_d98b74_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingroutingrule',
            index=models.Index(fields=['priority'], name='accounting__priorit_cfa9e7_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingroutingrule',
            index=models.Index(fields=['source', 'purpose', 'is_active'], name='accounting__source_7bb14a_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountingroutingrule',
            constraint=models.UniqueConstraint(fields=('source', 'purpose', 'account', 'tax_rate', 'cost_center'), name='unique_accounting_routing_rule_scope'),
        ),
        migrations.AddIndex(
            model_name='taxtransaction',
            index=models.Index(fields=['tax_rate'], name='accounting__tax_rat_2effdb_idx'),
        ),
        migrations.AddIndex(
            model_name='taxtransaction',
            index=models.Index(fields=['journal_entry'], name='accounting__journal_f6e844_idx'),
        ),
        migrations.AddIndex(
            model_name='taxtransaction',
            index=models.Index(fields=['journal_line'], name='accounting__journal_8c1e5a_idx'),
        ),
        migrations.AddIndex(
            model_name='taxtransaction',
            index=models.Index(fields=['direction'], name='accounting__directi_9c90c4_idx'),
        ),
        migrations.AddIndex(
            model_name='taxtransaction',
            index=models.Index(fields=['transaction_date'], name='accounting__transac_fd7ebc_idx'),
        ),
        migrations.AddIndex(
            model_name='taxtransaction',
            index=models.Index(fields=['source_type'], name='accounting__source__ca48ad_idx'),
        ),
        migrations.AddIndex(
            model_name='taxtransaction',
            index=models.Index(fields=['source_id'], name='accounting__source__27f273_idx'),
        ),
        migrations.AddIndex(
            model_name='taxtransaction',
            index=models.Index(fields=['currency'], name='accounting__currenc_066b7b_idx'),
        ),
    ]
