# Generated by Django 5.0.14 on 2026-05-19 10:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_accountingperiod_accountingroutingrule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-entry_date', '-id'], 'verbose_name': 'قيد يومية', 'verbose_name_plural': 'قيود اليومية'},
        ),
        migrations.AlterModelOptions(
            name='journalentryline',
            options={'ordering': ['journal_entry', 'sort_order', 'id'], 'verbose_name': 'سطر قيد', 'verbose_name_plural': 'أسطر القيود'},
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='accounting__account_aa34fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='accounting__parent__2641b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='accountingperiod',
            name='accounting__fiscal__c78858_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalentry',
            name='accounting__posting_07b5b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalentryline',
            name='accounting__journal_40cce9_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalentryline',
            name='accounting__account_bae40a_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalentryline',
            name='accounting__cost_ce_86bfe4_idx',
        ),
        migrations.AddField(
            model_name='account',
            name='purpose',
            field=models.CharField(choices=[('ACCOUNTS_RECEIVABLE', 'ذمم العملاء'), ('ACCOUNTS_PAYABLE', 'ذمم الموردين'), ('CASH', 'الصندوق'), ('BANK', 'البنك'), ('SALES_REVENUE', 'إيرادات المبيعات'), ('PLATFORM_SHARE_REVENUE', 'إيراد حصة النظام / المنصة'), ('OTHER_REVENUE', 'إيرادات أخرى'), ('OUTPUT_VAT', 'ضريبة مخرجات'), ('INPUT_VAT', 'ضريبة مدخلات'), ('VAT_PAYABLE', 'ضريبة مستحقة'), ('DISCOUNT_ALLOWED', 'خصم مسموح'), ('DISCOUNT_EARNED', 'خصم مكتسب'), ('COST_OF_SALES', 'تكلفة المبيعات'), ('EXPENSE', 'مصروف'), ('AGENT_CUSTODY', 'عهدة المندوبين'), ('AGENT_COMMISSION_EXPENSE', 'مصروف عمولة مندوب'), ('AGENT_DELIVERY_EXPENSE', 'مصروف توصيل مندوب'), ('AGENT_COMMISSION_PAYABLE', 'مستحقات مندوب'), ('AGENT_SETTLEMENT', 'تسويات مناديب'), ('BROKER_CUSTODY', 'عهدة الوسطاء'), ('BROKER_COMMISSION_EXPENSE', 'مصروف عمولة وسيط'), ('BROKER_COMMISSION_PAYABLE', 'مستحقات وسيط'), ('BROKER_SETTLEMENT', 'تسويات وسطاء'), ('PROVIDER_PAYABLE', 'مستحقات مقدم خدمة'), ('PROVIDER_CONTRACT_COMMISSION_EXPENSE', 'مصروف عمولة عقد مقدم خدمة'), ('GATEWAY_FEES', 'رسوم بوابة دفع'), ('ROUNDING', 'فروقات تقريب'), ('OPENING_EQUITY', 'حقوق أرصدة افتتاحية'), ('SUSPENSE', 'حساب معلق'), ('OTHER', 'أخرى')], db_index=True, default='OTHER', max_length=80, verbose_name='الغرض المحاسبي'),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='auto_post_agent_earnings',
            field=models.BooleanField(default=True, verbose_name='ترحيل استحقاقات المندوبين تلقائيًا'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='auto_post_agent_settlements',
            field=models.BooleanField(default=True, verbose_name='ترحيل تسويات المندوبين تلقائيًا'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='auto_post_broker_earnings',
            field=models.BooleanField(default=True, verbose_name='ترحيل استحقاقات الوسطاء تلقائيًا'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='auto_post_broker_settlements',
            field=models.BooleanField(default=True, verbose_name='ترحيل تسويات الوسطاء تلقائيًا'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='auto_post_cod_custody',
            field=models.BooleanField(default=True, verbose_name='ترحيل عهد COD تلقائيًا'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='افتراضية'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='currency',
            field=models.CharField(default='SAR', max_length=10, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='direction',
            field=models.CharField(choices=[('OUTPUT', 'ضريبة مبيعات'), ('INPUT', 'ضريبة مشتريات'), ('SETTLEMENT', 'تسوية ضريبية')], default='OUTPUT', max_length=20, verbose_name='اتجاه الضريبة'),
        ),
        migrations.AlterField(
            model_name='account',
            name='allow_manual_posting',
            field=models.BooleanField(default=True, verbose_name='السماح بالترحيل اليدوي'),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='كود الحساب'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_group',
            field=models.BooleanField(default=False, verbose_name='حساب تجميعي'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='حساب نظامي'),
        ),
        migrations.AlterField(
            model_name='account',
            name='nature',
            field=models.CharField(choices=[('DEBIT', 'مدين'), ('CREDIT', 'دائن')], max_length=10, verbose_name='طبيعة الحساب'),
        ),
        migrations.AlterField(
            model_name='accountingroutingrule',
            name='purpose',
            field=models.CharField(choices=[('ACCOUNTS_RECEIVABLE', 'ذمم العملاء'), ('ACCOUNTS_PAYABLE', 'ذمم الموردين'), ('CASH', 'الصندوق'), ('BANK', 'البنك'), ('SALES_REVENUE', 'إيرادات المبيعات'), ('PLATFORM_SHARE_REVENUE', 'إيراد حصة النظام / المنصة'), ('OTHER_REVENUE', 'إيرادات أخرى'), ('OUTPUT_VAT', 'ضريبة مخرجات'), ('INPUT_VAT', 'ضريبة مدخلات'), ('VAT_PAYABLE', 'ضريبة مستحقة'), ('DISCOUNT_ALLOWED', 'خصم مسموح'), ('DISCOUNT_EARNED', 'خصم مكتسب'), ('COST_OF_SALES', 'تكلفة المبيعات'), ('EXPENSE', 'مصروف'), ('AGENT_CUSTODY', 'عهدة المندوبين'), ('AGENT_COMMISSION_EXPENSE', 'مصروف عمولة مندوب'), ('AGENT_DELIVERY_EXPENSE', 'مصروف توصيل مندوب'), ('AGENT_COMMISSION_PAYABLE', 'مستحقات مندوب'), ('AGENT_SETTLEMENT', 'تسويات مناديب'), ('BROKER_CUSTODY', 'عهدة الوسطاء'), ('BROKER_COMMISSION_EXPENSE', 'مصروف عمولة وسيط'), ('BROKER_COMMISSION_PAYABLE', 'مستحقات وسيط'), ('BROKER_SETTLEMENT', 'تسويات وسطاء'), ('PROVIDER_PAYABLE', 'مستحقات مقدم خدمة'), ('PROVIDER_CONTRACT_COMMISSION_EXPENSE', 'مصروف عمولة عقد مقدم خدمة'), ('GATEWAY_FEES', 'رسوم بوابة دفع'), ('ROUNDING', 'فروقات تقريب'), ('OPENING_EQUITY', 'حقوق أرصدة افتتاحية'), ('SUSPENSE', 'حساب معلق'), ('OTHER', 'أخرى')], max_length=80, verbose_name='الغرض المحاسبي'),
        ),
        migrations.AlterField(
            model_name='accountingroutingrule',
            name='source',
            field=models.CharField(choices=[('SALES_INVOICE', 'فاتورة مبيعات'), ('PURCHASE_INVOICE', 'فاتورة مشتريات'), ('PAYMENT_RECEIPT', 'قبض دفعة'), ('PAYMENT_REFUND', 'استرداد دفعة'), ('TREASURY_INCOME', 'قبض خزينة'), ('TREASURY_EXPENSE', 'صرف خزينة'), ('TREASURY_TRANSFER', 'تحويل خزينة'), ('TREASURY_MANUAL_RECEIPT', 'سند قبض يدوي'), ('TREASURY_MANUAL_PAYMENT', 'سند صرف يدوي'), ('AGENT_COMMISSION', 'عمولة مندوب'), ('AGENT_EARNING', 'استحقاق مندوب'), ('AGENT_DELIVERY_FEE', 'قيمة توصيل مندوب'), ('AGENT_COD_CUSTODY', 'عهدة COD مندوب'), ('AGENT_SETTLEMENT', 'تسوية مندوب'), ('BROKER_COMMISSION', 'عمولة وسيط'), ('BROKER_EARNING', 'استحقاق وسيط'), ('BROKER_COD_CUSTODY', 'عهدة COD وسيط'), ('BROKER_SETTLEMENT', 'تسوية وسيط'), ('PLATFORM_SHARE', 'حصة النظام'), ('PROVIDER_CONTRACT', 'عقد مقدم خدمة'), ('EXPENSE', 'مصروف'), ('INCOME', 'إيراد'), ('TAX_SETTLEMENT', 'تسوية ضريبية'), ('OPENING_BALANCE', 'رصيد افتتاحي'), ('OTHER', 'أخرى')], max_length=50, verbose_name='مصدر العملية'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='is_group',
            field=models.BooleanField(default=False, verbose_name='مركز تكلفة تجميعي'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='رقم القيد'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='is_auto_posted',
            field=models.BooleanField(default=False, verbose_name='قيد آلي'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='posting_source',
            field=models.CharField(choices=[('MANUAL', 'يدوي'), ('OPENING_BALANCE', 'رصيد افتتاحي'), ('ORDER', 'طلب'), ('INVOICE', 'فاتورة'), ('PAYMENT', 'دفعة'), ('REFUND', 'استرداد'), ('AGENT_COMMISSION', 'عمولة مندوب'), ('AGENT_EARNING', 'استحقاق مندوب'), ('AGENT_DELIVERY_FEE', 'قيمة توصيل مندوب'), ('AGENT_COD_CUSTODY', 'عهدة COD مندوب'), ('AGENT_SETTLEMENT', 'تسوية مندوب'), ('BROKER_COMMISSION', 'عمولة وسيط'), ('BROKER_EARNING', 'استحقاق وسيط'), ('BROKER_COD_CUSTODY', 'عهدة COD وسيط'), ('BROKER_SETTLEMENT', 'تسوية وسيط'), ('TREASURY', 'خزينة'), ('TREASURY_TRANSFER', 'تحويل خزينة'), ('TREASURY_RECEIPT', 'سند قبض'), ('TREASURY_PAYMENT', 'سند صرف'), ('PROVIDER_CONTRACT', 'عقد مقدم خدمة'), ('EXPENSE', 'مصروف'), ('INCOME', 'إيراد'), ('TAX', 'ضريبة'), ('ADJUSTMENT', 'تسوية'), ('SYSTEM', 'نظام'), ('OTHER', 'أخرى')], default='MANUAL', max_length=30, verbose_name='مصدر القيد'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='مرجع'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_entries', to='accounting.journalentry', verbose_name='عكس القيد'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reversed_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_reversed_entries', to='accounting.journalentry', verbose_name='القيد العكسي'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(blank=True, max_length=80, verbose_name='نوع المصدر'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='party_type',
            field=models.CharField(blank=True, max_length=80, verbose_name='نوع الطرف'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتيب السطر'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='source_line_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='معرف السطر من المصدر'),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم الضريبة'),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='purchase_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_purchase_rates', to='accounting.account', verbose_name='حساب ضريبة المشتريات'),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('15.0000'), max_digits=7, verbose_name='النسبة'),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='sales_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_sales_rates', to='accounting.account', verbose_name='حساب ضريبة المبيعات'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['purpose'], name='accounting__purpose_bf583f_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalyear',
            index=models.Index(fields=['is_default'], name='accounting__is_defa_59a20c_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['reversal_of'], name='accounting__reversa_0a607d_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['reversed_entry'], name='accounting__reverse_713f97_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['direction'], name='accounting__directi_227349_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.UniqueConstraint(fields=('fiscal_year', 'name'), name='unique_accounting_period_name_per_year'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.UniqueConstraint(fields=('fiscal_year', 'start_date', 'end_date'), name='unique_accounting_period_range_per_year'),
        ),
    ]
