# Generated by Django 5.0.14 on 2026-04-28 19:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Service Item Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('included_quantity', models.PositiveIntegerField(default=1, verbose_name='Included Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Unit Price')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Discount Rate (%)')),
                ('requires_provider', models.BooleanField(db_index=True, default=True, verbose_name='Requires Provider')),
                ('is_optional', models.BooleanField(db_index=True, default=False, verbose_name='Is Optional')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Product Service Item',
                'verbose_name_plural': 'Product Service Items',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='allow_agent_sale',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Allow Agent Sale'),
        ),
        migrations.AddField(
            model_name='product',
            name='allow_provider_sale',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Allow Provider Sale'),
        ),
        migrations.AddField(
            model_name='product',
            name='can_be_ordered',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Can Be Ordered'),
        ),
        migrations.AddField(
            model_name='product',
            name='can_be_used_in_contracts',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Can Be Used In Contracts'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_agent_commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Default Agent Commission Rate (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='fulfillment_type',
            field=models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical'), ('both', 'Both'), ('service_based', 'Service Based'), ('none', 'None')], db_index=True, default='digital', max_length=30, verbose_name='Fulfillment Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_discount_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Max Discount Rate (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_provider',
            field=models.BooleanField(db_index=True, default=False, help_text='Use this for services/programs that must be linked to a provider or contract.', verbose_name='Requires Provider'),
        ),
        migrations.AddField(
            model_name='productpricingtier',
            name='agent_commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Agent Commission Rate (%)'),
        ),
        migrations.AddField(
            model_name='productpricingtier',
            name='currency_code',
            field=models.CharField(db_index=True, default='SAR', max_length=10, verbose_name='Currency Code'),
        ),
        migrations.AddField(
            model_name='productpricingtier',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Discount Rate (%)'),
        ),
        migrations.AddField(
            model_name='productpricingtier',
            name='ends_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Ends At'),
        ),
        migrations.AddField(
            model_name='productpricingtier',
            name='max_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum Quantity'),
        ),
        migrations.AddField(
            model_name='productpricingtier',
            name='min_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Minimum Quantity'),
        ),
        migrations.AddField(
            model_name='productpricingtier',
            name='pricing_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('customer', 'Customer'), ('agent', 'Agent'), ('provider', 'Provider'), ('contract', 'Contract'), ('promotional', 'Promotional')], db_index=True, default='standard', max_length=30, verbose_name='Pricing Type'),
        ),
        migrations.AddField(
            model_name='productpricingtier',
            name='provider_share_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Provider Share Rate (%)'),
        ),
        migrations.AddField(
            model_name='productpricingtier',
            name='starts_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Starts At'),
        ),
        migrations.AddField(
            model_name='productpricingtier',
            name='system_share_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='System Share Rate (%)'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['billing_type'], name='products_pr_billing_fca9d4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['fulfillment_type'], name='products_pr_fulfill_21a740_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['can_be_ordered', 'status'], name='products_pr_can_be__bc059f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['can_be_used_in_contracts', 'status'], name='products_pr_can_be__b7af66_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['requires_provider'], name='products_pr_require_62f5b0_idx'),
        ),
        migrations.AddIndex(
            model_name='productbenefit',
            index=models.Index(fields=['product', 'is_active'], name='products_pr_product_439618_idx'),
        ),
        migrations.AddIndex(
            model_name='productbenefit',
            index=models.Index(fields=['sort_order'], name='products_pr_sort_or_c266f5_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['code'], name='products_pr_code_dbab3f_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['name'], name='products_pr_name_863729_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['category_type', 'status'], name='products_pr_categor_0c1d13_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['created_at'], name='products_pr_created_e88bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='productpricingtier',
            index=models.Index(fields=['product', 'is_active'], name='products_pr_product_f92040_idx'),
        ),
        migrations.AddIndex(
            model_name='productpricingtier',
            index=models.Index(fields=['product', 'pricing_type'], name='products_pr_product_2cacb9_idx'),
        ),
        migrations.AddIndex(
            model_name='productpricingtier',
            index=models.Index(fields=['pricing_type', 'is_active'], name='products_pr_pricing_ccefba_idx'),
        ),
        migrations.AddIndex(
            model_name='productpricingtier',
            index=models.Index(fields=['currency_code'], name='products_pr_currenc_4a8f15_idx'),
        ),
        migrations.AddIndex(
            model_name='productpricingtier',
            index=models.Index(fields=['starts_at', 'ends_at'], name='products_pr_starts__41d383_idx'),
        ),
        migrations.AddIndex(
            model_name='productpricingtier',
            index=models.Index(fields=['sort_order'], name='products_pr_sort_or_83db62_idx'),
        ),
        migrations.AddField(
            model_name='productserviceitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='products.product', verbose_name='Product'),
        ),
        migrations.AddIndex(
            model_name='productserviceitem',
            index=models.Index(fields=['product', 'is_active'], name='products_pr_product_d26c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='productserviceitem',
            index=models.Index(fields=['requires_provider'], name='products_pr_require_3c14c1_idx'),
        ),
        migrations.AddIndex(
            model_name='productserviceitem',
            index=models.Index(fields=['is_optional'], name='products_pr_is_opti_306f60_idx'),
        ),
        migrations.AddIndex(
            model_name='productserviceitem',
            index=models.Index(fields=['sort_order'], name='products_pr_sort_or_752cd3_idx'),
        ),
    ]
