# Generated by Django 5.0.14 on 2026-05-10 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productserviceitem_product_allow_agent_sale_and_more'),
        ('providers', '0003_providerdocument_provider_commercial_registration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_offer',
            field=models.BooleanField(db_index=True, default=False, help_text='Marks this product as a customer-facing offer or medical program.', verbose_name='Is Offer'),
        ),
        migrations.AddField(
            model_name='product',
            name='marketing_image_alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Marketing Alt Text'),
        ),
        migrations.AddField(
            model_name='product',
            name='marketing_image_drive_file_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Marketing Drive File ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='marketing_image_drive_view_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Marketing Drive View URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='marketing_image_folder_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Marketing Folder ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='marketing_image_folder_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Marketing Folder URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='marketing_image_url',
            field=models.URLField(blank=True, help_text='Large marketing image used for landing, offers, mobile app, and campaigns.', max_length=1000, verbose_name='Marketing Image URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_badge',
            field=models.CharField(blank=True, help_text='Example: Limited Offer, Free Card, New Program.', max_length=100, verbose_name='Offer Badge'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_end_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Offer End Date'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_start_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Offer Start Date'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Offer Subtitle'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_terms',
            field=models.TextField(blank=True, verbose_name='Offer Terms'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_title',
            field=models.CharField(blank=True, help_text='Optional marketing title for landing/offers/mobile display.', max_length=255, verbose_name='Offer Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Optional provider for provider-specific medical programs or offers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='providers.provider', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_on_landing',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Show On Landing'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_on_mobile',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Show On Mobile'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_on_offers',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Show On Offers'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_image_alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Thumbnail Alt Text'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_image_drive_file_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Thumbnail Drive File ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_image_drive_view_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Thumbnail Drive View URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_image_folder_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Thumbnail Folder ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_image_folder_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Thumbnail Folder URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_image_url',
            field=models.URLField(blank=True, help_text='Small symbolic image used inside the admin/system UI.', max_length=1000, verbose_name='Thumbnail Image URL'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['provider'], name='products_pr_provide_4b64d6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['provider', 'product_type'], name='products_pr_provide_11e721_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['provider', 'status'], name='products_pr_provide_012bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_offer', 'status'], name='products_pr_is_offe_17b4e9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['show_on_landing', 'status'], name='products_pr_show_on_e61d74_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['show_on_mobile', 'status'], name='products_pr_show_on_05cad2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['show_on_offers', 'status'], name='products_pr_show_on_8fb5eb_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['offer_start_date', 'offer_end_date'], name='products_pr_offer_s_bbf89b_idx'),
        ),
    ]
