# Generated by Django 5.0.14 on 2026-05-14 12:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_slug'),
        ('providers', '0003_providerdocument_provider_commercial_registration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default catalog discount. Provider-specific discount is stored in ContractProduct.', max_digits=5, verbose_name='Default Discount Percentage (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_duration',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Has Duration'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_expiry',
            field=models.BooleanField(db_index=True, default=False, help_text='If enabled, product visibility/orderability can be limited by valid_from/valid_until.', verbose_name='Has Expiry'),
        ),
        migrations.AddField(
            model_name='product',
            name='valid_from',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Valid From'),
        ),
        migrations.AddField(
            model_name='product',
            name='valid_until',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Valid Until'),
        ),
        migrations.AlterField(
            model_name='product',
            name='can_be_used_in_contracts',
            field=models.BooleanField(db_index=True, default=True, help_text='Medical services should usually be usable in contracts.', verbose_name='Can Be Used In Contracts'),
        ),
        migrations.AlterField(
            model_name='product',
            name='duration_value',
            field=models.PositiveIntegerField(default=0, help_text='Example: 12 months / 30 days / 1 year.', verbose_name='Duration Value'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_offer',
            field=models.BooleanField(db_index=True, default=False, help_text='Marks this catalog product as a customer-facing general offer.', verbose_name='Is Offer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Price Before Discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('membership', 'Membership'), ('card', 'Card'), ('medical_service', 'Medical Service'), ('program', 'Program'), ('service', 'Service'), ('other', 'Other')], db_index=True, default='card', help_text='Catalog type: card, medical service, membership, program, etc.', max_length=30, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Deprecated. Do not use for new products. Provider-specific pricing/offers must use ContractProduct.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_products', to='providers.provider', verbose_name='Legacy Provider'),
        ),
        migrations.AlterField(
            model_name='product',
            name='requires_provider',
            field=models.BooleanField(db_index=True, default=False, help_text='If true, the product requires a ContractProduct/provider offer at order time.', verbose_name='Requires Provider'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price After Discount'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_type',
            field=models.CharField(choices=[('membership', 'Membership'), ('card', 'Card'), ('medical_service', 'Medical Service'), ('program', 'Program'), ('service', 'Service'), ('other', 'Other')], db_index=True, default='program', max_length=30, verbose_name='Category Type'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['has_duration'], name='products_pr_has_dur_e48a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['has_expiry'], name='products_pr_has_exp_54f630_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['valid_from', 'valid_until'], name='products_pr_valid_f_8b47c8_idx'),
        ),
    ]
